#!/bin/sh
export HOME=/root
export USER=root
export LOGNAME=root
export SHELL=/bin/brush
export PATH=/bin:/usr/bin:/sbin:/usr/sbin
export TERM=${TERM:-linux}
if [ -r /etc/profile ]; then
    . /etc/profile
fi
exec /bin/brush
