[workspace]
members = [
    "src/tools/mattos-build",
    "src/userland/init"
]
exclude = [
    "src/userland/grep",
    "src/userland/sed",
    "src/userland/findutils",
    "src/userland/diffutils"
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
authors = ["MattOS Contributors"]
repository = "https://example.invalid/mattos"
