[workspace]
members = [
    "src/tools/mattos-build",
    "src/system/installer",
    "src/userland/init"
]
exclude = [
    "src/userland/grep",
    "src/userland/sed",
    "src/userland/findutils",
    "src/userland/diffutils",
    "src/system/auth/sudo-rs"
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
authors = ["MattOS Contributors"]
repository = "https://example.invalid/mattos"

[profile.dev.package.serde_json]
opt-level = 3

[profile.dev.package.sha2]
opt-level = 3
