schema_version = 2
component = "appstream"
repo = "https://github.com/ximion/appstream.git"
branch = "v1.1.6"
imported_commit = "c046aa7e28e1950d44874bc5bdfc2268a338255f"
imported_at_utc = "2026-08-27T22:00:54.244597283+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/appstream"
upstream_tree = "fc200cd797152b0782565617704567231cf60d30"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "ecbe1c3366e844e676d07538ee9e1599bae3ffee10a46a18d745ddf8c3ae06d3"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
