schema_version = 2
component = "apt"
repo = "https://salsa.debian.org/apt-team/apt.git"
branch = "main"
imported_commit = "5e6dcc8d0c8bdce61e9cc7f497abadb5349d509a"
imported_at_utc = "2026-08-02T01:52:42.523214229+00:00"
sync_method = "copy"
destination_path = "src/system/packages/apt"
upstream_tree = "17a0f75942965e23f2e92b8901086041aff2ba88"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f449ed5ad379587bb9ba72eb9353552d603969d594bf3aaabd31d2d997ee6992"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/apt/manifest.toml"
patch_manifest_sha256 = "326214de72d7add30beba1f730df8e9d460ce9be2551601f03263f0e3bc15a28"
