schema_version = 2
component = "attica"
repo = "https://invent.kde.org/frameworks/attica.git"
branch = "v6.26.0"
imported_commit = "aef3c6951afb0c5a850957bcfdafdc129f442b5b"
imported_at_utc = "2026-09-13T08:20:28.682118185+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/attica"
upstream_tree = "a8bc523c016429023b1d6d38bf95cce2597c4ebc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d2037d3c1e53d78025041536a11f61869a2f6e92f1444d2fa83f140b696bd33b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/attica/manifest.toml"
patch_manifest_sha256 = "acac4660ff8b83ec78a903307b1cc39b82528eb9ba02963aa3f3e49d365ccab3"
lfs_policy = "none"
lfs_policy_sha256 = "none"
