schema_version = 2
component = "attr"
repo = "https://git.savannah.nongnu.org/git/attr.git"
branch = "v2.6.0"
imported_commit = "c440855d6b33446edf4b5eb1a2d892281f15a99b"
imported_at_utc = "2026-08-03T05:26:42.969680060+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/attr"
upstream_tree = "0e2a995cca3e6c638de01dea0c3a478d8068908f"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "60a24946b56738c5168e7cd60a3149f93c91f77ccf6596ca5b5c5b6857b2b8c2"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
