schema_version = 2
component = "aurorae"
repo = "https://invent.kde.org/plasma/aurorae.git"
branch = "v6.6.5"
imported_commit = "9c314e075f70a1132cf16c233e24c44744e59e39"
imported_at_utc = "2026-09-25T05:09:06.525356802+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/aurorae"
upstream_tree = "d37b8998b3b3da428e903eb9b9b9b7fb301d7848"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "1fb70d79c96ecf82dd428553c8e961f5c98afa714b003389585ee300824b1e50"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
