schema_version = 2
component = "autoconf"
repo = "https://git.savannah.gnu.org/git/autoconf.git"
branch = "v2.73"
imported_commit = "44d712a26b0e14931bf2df57e2c9b80a2747dfce"
imported_at_utc = "2026-09-30T05:51:49.604506827+00:00"
sync_method = "copy"
destination_path = "src/build-tools/autoconf"
upstream_tree = "7d72c8b4f7a315ad6aeb3c7d44fbfd91552812c0"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "460e49a6658771c91e26357005e3b05984b45cadff6b2d4a03b712c738c07ecb"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-03-20T19:07:41Z"
