schema_version = 2
component = "autoconf-archive"
repo = "https://git.savannah.gnu.org/git/autoconf-archive.git"
branch = "v2023.02.20"
imported_commit = "4cd9fa38f0f6cd6998a8d25d25824a0d59ee4fea"
imported_at_utc = "2026-09-09T01:18:02.920161998+00:00"
sync_method = "copy"
destination_path = "src/build-support/autoconf-archive"
upstream_tree = "a0c2e8cab0d815fc5033b1c8262653de026c7c63"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "006d1698716af02f1aa0f6cf7b7c51ef80f2d6de3303be9cc969152cfc78647e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
