schema_version = 2
component = "bluez"
repo = "https://github.com/bluez/bluez.git"
branch = "5.87"
imported_commit = "65d11edee469c24dcc8d075b8be9c040cebaaf98"
imported_at_utc = "2026-09-18T05:03:38.274939714+00:00"
sync_method = "copy"
destination_path = "src/system/services/bluez"
upstream_tree = "e87954670fd82e2ec4361e41a6fd0ae7412750f4"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "c5dbc3e1937aae40f65dc1145c6d5e43ae53f962d1d0b9c97b349781c5fa51ce"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
