schema_version = 2
component = "breeze-icons"
repo = "https://github.com/KDE/breeze-icons.git"
branch = "v6.26.0"
imported_commit = "872cc3cc073f857e2160105216488585e340d314"
imported_at_utc = "2026-09-13T01:31:21.598190658+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/breeze-icons"
upstream_tree = "d8a4d48c0ef124e90deaf1ce7cedbb33cfc9f87a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d4f39d099eb579fd679ad1e44a3d7b02650d280133a48a0968f31eaa422b3c84"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
