schema_version = 2
component = "breeze"
repo = "https://invent.kde.org/plasma/breeze.git"
branch = "v6.6.5"
imported_commit = "bfe46a06e92a196fe3051706051d5c5e2d497e92"
imported_at_utc = "2026-09-12T19:36:02.780555319+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/breeze"
upstream_tree = "0798b3c1894a3963b7475fe45276d8a7768c6bb7"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "8f284cb5b4610fe21d133464f11d1bf0035e6c32d188d19cd5b7a6800c04068e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
