schema_version = 2
component = "brush"
repo = "https://github.com/reubeno/brush.git"
branch = "main"
imported_commit = "71afef7ce79ad2fd94833fa4f93fa5486c86c56b"
imported_at_utc = "2026-07-31T03:54:34.318185600+00:00"
sync_method = "copy"
destination_path = "src/userland/brush"
upstream_tree = "c90a1ebd478bc95dc54095e3fa9e7be030041165"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "767e1a55a66107c060002b0b273348735e67ca0074dab4fddd501d8f5f0e0dd4"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/brush/manifest.toml"
patch_manifest_sha256 = "4ac8fb49466401acaac6b6bb9c16bc49c24e951ed5c597d5efa80fbc07f02883"
