schema_version = 2
component = "bsdiff"
repo = "https://github.com/mendsley/bsdiff.git"
branch = "master"
imported_commit = "b817e9491cf7b8699c8462ef9e2657ca4ccd7667"
imported_at_utc = "2026-08-27T21:03:39.781150033+00:00"
sync_method = "copy"
destination_path = "src/system/packages/ostree/bsdiff"
upstream_tree = "287009d922a7c2bcaf7cce42b0a46caa88ccd801"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "843a4757180ab1713a36b41f04d73d1bff5d36285c4cc3100fc22f6be49d90a9"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
