schema_version = 2
component = "btrfs-progs"
repo = "https://github.com/kdave/btrfs-progs.git"
branch = "v6.17"
imported_commit = "c03e29f083678f47a7d7d810db4d21d905979b77"
imported_at_utc = "2026-08-12T02:23:01.729224483+00:00"
sync_method = "copy"
destination_path = "src/system/storage/btrfs-progs"
upstream_tree = "0787a8c50c111f4758a260c33906fd32895a9be9"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "cb2302eb177873d1b472b8f0be94f05f037ff1910205495872794bba49a901a9"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
