schema_version = 2
component = "bubblewrap"
repo = "https://github.com/containers/bubblewrap.git"
branch = "v0.11.0"
imported_commit = "9ca3b05ec787acfb4b17bed37db5719fa777834f"
imported_at_utc = "2026-08-29T00:29:25.770328248+00:00"
sync_method = "copy"
destination_path = "src/system/security/bubblewrap"
upstream_tree = "2238890e51e3c2e829f802b0cb795dd61caa6d74"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "a26460071afe0af869512ca77e7e4f0435aad3d07ad22f7f56d235058db15e9c"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
