schema_version = 2
component = "calamares"
repo = "https://codeberg.org/calamares/calamares.git"
branch = "v3.4.3"
imported_commit = "af2eaf829b7c60ae5b69b9fe68f9158dc98d3331"
imported_at_utc = "2026-09-11T20:38:10.595939543+00:00"
sync_method = "copy"
destination_path = "src/system/installer/calamares/upstream"
upstream_tree = "add63969af9258d1fe13efb87f215bb6ea63168a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "af16609f778d6d77f3410a7c30cc6bfdaa77f1d7a6e669593ae8caa198f97294"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/calamares/manifest.toml"
patch_manifest_sha256 = "288fa655bc397320c17e2d33db19c4ea0f1374295613075b37c6939c66234bcf"
lfs_policy = "none"
lfs_policy_sha256 = "none"
