schema_version = 2
component = "cmake"
repo = "https://github.com/Kitware/CMake.git"
branch = "v4.4.3"
imported_commit = "af7ecc8c294d153b0120813776e1fa11c5bfe4a1"
imported_at_utc = "2026-09-30T00:30:38.525614235+00:00"
sync_method = "copy"
destination_path = "src/build-tools/cmake"
upstream_tree = "1125ebf0f43169995f4934aac033721189ee87fc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "07c31902bd5c1c167d0dd513bcefc1020617fc9e5a7fc68c73d0dbd279e82769"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-08-25T15:10:30Z"
