schema_version = 2
component = "coreutils"
repo = "https://github.com/uutils/coreutils.git"
branch = "main"
imported_commit = "91f6543cad721aba0bf17806e803e84a116f8603"
imported_at_utc = "2026-07-31T03:54:42.179070400+00:00"
sync_method = "copy"
destination_path = "src/userland/coreutils"
upstream_tree = "3b6a74d1c9d520834b64b831a23b4192a5120848"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "7c57f8cd9e3773ad3ad0eebc1c96e8063af08dd00a03bd11614a7efec8891868"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
