schema_version = 2
component = "cosmic-notifications"
repo = "https://github.com/pop-os/cosmic-notifications.git"
branch = "master"
imported_commit = "7c723b7705ec77b1ad5396a1baa9ae1c0cb5a0da"
imported_at_utc = "2026-08-15T23:34:13.655794968+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-notifications"
upstream_tree = "37030f3154f5c986df3911965c7f4315b242f8a6"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "517adf3148a7801f20f7f9ce302b8515e97121856a98c14a9a5243b550f6171c"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
