schema_version = 2
component = "cosmic-protocols"
repo = "https://github.com/pop-os/cosmic-protocols.git"
branch = "main"
imported_commit = "32283d76a8d0342da74c4cc022a533c52dcf378f"
imported_at_utc = "2026-08-12T20:14:36.161769306+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-protocols"
upstream_tree = "92a5b9153fd414fa1cb446ebdd5043a8d66e5748"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "4cb6e505ae4f2196f0e0d87af8dad42ed0affc23503404ab522daa1ea6eef4bd"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
