schema_version = 2
component = "cosmic-bg"
repo = "https://github.com/pop-os/cosmic-bg.git"
branch = "master"
imported_commit = "76e89e6aff4224e3a820cbe71c74ee91adb60d03"
imported_at_utc = "2026-08-15T23:34:16.183455174+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-bg"
upstream_tree = "c5e5eea9107716d53e61ef18df79c1e81a288e63"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b15c1d710582bf5263e628e0bff4304f456e243d96f9863a667427b29b1ac921"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
