schema_version = 2
component = "cosmic-settings"
repo = "https://github.com/pop-os/cosmic-settings.git"
branch = "master"
imported_commit = "7287257ec9f2ca301642bd4800f391ad9079d3e9"
imported_at_utc = "2026-08-15T23:34:10.200587179+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-settings"
upstream_tree = "d990f6e9f0af3a711ba2259468b91f50636c62aa"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "fdb4872ba3c3f06da7b11d0133f1588ff3c2a881cdf17ad40ff2d81fd115f61c"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
