schema_version = 2
component = "cosmic-randr"
repo = "https://github.com/pop-os/cosmic-randr.git"
branch = "master"
imported_commit = "6e8e795970fa06d434af22775e415b517f7552d3"
imported_at_utc = "2026-08-15T23:34:23.798165403+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-randr"
upstream_tree = "9107e0177775b45a7b35ee72f54fad096a9c0dad"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "18ffe3ef1baf9778f9292b3bedaafcac488d7ef24a64aac08c340b8a9ba1375d"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
