schema_version = 2
component = "cosmic-workspaces"
repo = "https://github.com/pop-os/cosmic-workspaces-epoch.git"
branch = "master"
imported_commit = "8faab4c2a92f438a704d072e3c5aa9526d2acc88"
imported_at_utc = "2026-08-15T23:34:17.357685859+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-workspaces"
upstream_tree = "023924d9c4ddb36a7c07397babab83edd46dd703"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "a150b62f0d42b97ace752dd35bdd5686b72c95bc086350bee128b3f9c51176e2"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
