schema_version = 2
component = "cosmic-iced"
repo = "https://github.com/pop-os/iced.git"
branch = "master"
imported_commit = "7918b2826ec8ad4f9e0032f6a21286bac431e482"
imported_at_utc = "2026-08-12T20:14:34.961244067+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/iced"
upstream_tree = "3694a6d29407ec2ce5c68cd963d98444b2a047f0"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "75b8a3c60a02e363fef875969326d33b9384e057333ab9e5d24297790e25da1b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
