schema_version = 2
component = "cosmic-greeter"
repo = "https://github.com/pop-os/cosmic-greeter.git"
branch = "master"
imported_commit = "d39915ae2381424d406cd511a2310ef928144f4c"
imported_at_utc = "2026-08-15T23:34:03.140118045+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-greeter"
upstream_tree = "af9636f6e4de953d60547ed76027d11f4f7506ad"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "c4fda124a382a9bad3cdbdef402a9aadf05fd94c23d4252a2b75cab16c448766"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
