schema_version = 2
component = "cosmic-files"
repo = "https://github.com/pop-os/cosmic-files.git"
branch = "master"
imported_commit = "24e34eaa0f0acf4e24ea1338ad4bbde3a138e1f3"
imported_at_utc = "2026-08-15T23:34:18.711641497+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-files"
upstream_tree = "a5af87ef41a602d203cffb2f71a6a53c8c7cbbad"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "2656b654b00fc7008c6191f3fc37be00def667bbff8b1a63100c0959a0d55a4f"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
