schema_version = 2
component = "cosmic-store"
repo = "https://github.com/pop-os/cosmic-store.git"
branch = "master"
imported_commit = "ca4615b22889bbecb83c614e1b52d8af97ef4aca"
imported_at_utc = "2026-08-27T20:25:01.075546272+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-store"
upstream_tree = "22d5cb0e85d0dd34681d89cf60b424005cc8b7ab"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "2ee412a2fb6545fd553dd447138e62b0e23fa9c403b7cf6238448942188359b7"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
