schema_version = 2
component = "cosmic-term"
repo = "https://github.com/pop-os/cosmic-term.git"
branch = "master"
imported_commit = "543cbb0cb818e1ef724d7f917ca562af44340e47"
imported_at_utc = "2026-08-15T23:34:21.080449225+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-term"
upstream_tree = "829b430a88261ca9e5c2c0784254d34dbe8da303"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "4aeb4434bb863503a60d84dc4751fbd45cafda250bfabca3474759fcbc978ecc"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
