schema_version = 2
component = "cosmic-applets"
repo = "https://github.com/pop-os/cosmic-applets.git"
branch = "master"
imported_commit = "ec8ffdc85d1f316b387cf89672609933064e6e88"
imported_at_utc = "2026-08-15T23:34:05.959052619+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-applets"
upstream_tree = "0bc1acec238f5278c02b201d0d92c0570de0fe15"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b6ec179f773397a94523ecf273fe8bce02ae9eadbc1d5728798ae127e3ac63a0"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
