schema_version = 2
component = "cosmic-edit"
repo = "https://github.com/pop-os/cosmic-edit.git"
branch = "master"
imported_commit = "4ac0da3af97207fb3807375928812f23ec04161f"
imported_at_utc = "2026-08-21T18:53:41.094558982+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-edit"
upstream_tree = "262725d98bfadc7b993535f236936ed453dbe546"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "478edda4d4108ac989ed5f640eae31d5635456b21226120648fc600f6289b222"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
