schema_version = 2
component = "cosmic-osd"
repo = "https://github.com/pop-os/cosmic-osd.git"
branch = "master"
imported_commit = "20a2055dfc0eed78b417f0ecd38cc15807df3285"
imported_at_utc = "2026-08-15T23:34:14.884802650+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-osd"
upstream_tree = "b0f57ebf66a0e1e5afba89ff3db2edc212353f61"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "2f2d9289257f425c90c358e8ff77595c6eae738017bdffedcd293d0459604fde"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
