schema_version = 2
component = "cosmic-settings-daemon"
repo = "https://github.com/pop-os/cosmic-settings-daemon.git"
branch = "master"
imported_commit = "21a9692b53fcbffa0f18f7d0a12bf0f9d5bd0590"
imported_at_utc = "2026-08-15T23:34:12.523563900+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-settings-daemon"
upstream_tree = "20a50ac930eadb348006eb6280f783bda837cad5"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "29692458cf8e8c120ed6da45a6f16f1d551a8f13d9c3df4e3994479aea4a3646"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
