schema_version = 2
component = "cosmic-calculator"
repo = "https://github.com/cosmic-utils/calculator.git"
branch = "main"
imported_commit = "1b614b95036e41333219b5c0d91853550b2439af"
imported_at_utc = "2026-08-27T16:13:22.782927470+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-calculator"
upstream_tree = "a1e02a498ac115cd3b3b4a799da84e7d0aa8d1ee"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f84defb3faa1309739ebf1268d3792c79f9494298a7224b59615092511498929"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
