schema_version = 2
component = "cosmic-icons"
repo = "https://github.com/pop-os/cosmic-icons.git"
branch = "master"
imported_commit = "b78b059636ed967ad7c6f120709c7d29b2bafac1"
imported_at_utc = "2026-08-15T23:34:22.613335806+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-icons"
upstream_tree = "8e62c6eaa970ab25f57f0fd53401279f16d6b7f8"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "bb04fb87a53271d7421cd72cd75ef7879a581e9b538708a5c4c457e63985cc09"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
