schema_version = 2
component = "cosmic-panel"
repo = "https://github.com/pop-os/cosmic-panel.git"
branch = "master"
imported_commit = "d6699ffc423a3830bf4cab7e2c7f08a173e998f0"
imported_at_utc = "2026-08-15T23:34:04.406190079+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-panel"
upstream_tree = "75758bc792b913a77ba5f8afa5bdcbb93d8ce67a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "8a4c01f6e4c5dabb8f2127094cc00d6c531a503e49300545a3a7b6b5b9b7161a"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
