schema_version = 2
component = "cosmic-idle"
repo = "https://github.com/pop-os/cosmic-idle.git"
branch = "master"
imported_commit = "c95d066b5b640509a6369634b669ca60dc50e168"
imported_at_utc = "2026-09-10T02:08:09.972856216+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-idle"
upstream_tree = "6b96314ca08f621857e9c0ddad0da94f9854a54e"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "265a867b0720983f27e52f4c768c063f427481e437910f7eb05e9c06e868fe47"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
