schema_version = 2
component = "cosmic-tweaks"
repo = "https://github.com/cosmic-utils/tweaks.git"
branch = "main"
imported_commit = "069c31b7b1beffddf744b28f8f056ace972830bc"
imported_at_utc = "2026-08-19T20:04:07.101790623+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-tweaks"
upstream_tree = "e9ea514ee5ec0056f9c2516d35e28e9eddf9f124"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b2732ee0729a55dc021723918275faa22874d2fb5cf2b3c2b064f6dec49d4bf0"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/cosmic-tweaks/manifest.toml"
patch_manifest_sha256 = "aad3b0f4f0a9fe35aab78e4abbf420a3d67322c2010bcaf05929fae9a035915d"
lfs_policy = "none"
lfs_policy_sha256 = "none"
