schema_version = 2
component = "cosmic-monitor"
repo = "https://github.com/pop-os/cosmic-monitor.git"
branch = "master"
imported_commit = "ee634d59b97022f091cdb64f4519886e2c72bf80"
imported_at_utc = "2026-08-27T16:14:54.819265043+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-monitor"
upstream_tree = "6bdbad291c0742cfdba7d871f8c0b7df1b3cdef5"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "0dfcce52cfdeea78d1bf272036860dbf5c60aa8057ee99e5c8f5c9828f56fce1"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
