schema_version = 2
component = "cosmic-comp"
repo = "https://github.com/pop-os/cosmic-comp.git"
branch = "master"
imported_commit = "693d1ad775193deb95a33810b5eac59684ca2ac0"
imported_at_utc = "2026-08-13T07:21:04.839909071+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/cosmic-comp"
upstream_tree = "0017bc3f47da8be017d4d332ab76c99049486a9f"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b93c98931c9c123084a896dab1bd80b723c58f0f149c04e64fbd00c68dd62cb5"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/cosmic-comp/manifest.toml"
patch_manifest_sha256 = "7b9c6ae9c405f5902700b93e4285c429dee23d802bf4dd3b6b5eb9ff8d422317"
lfs_policy = "none"
lfs_policy_sha256 = "none"
