schema_version = 2
component = "cozy"
repo = "https://github.com/takakix2/cozy.git"
branch = "main"
imported_commit = "c43a1d0f118f73d09e4a7414a3412479903e6bfe"
imported_at_utc = "2026-08-21T18:53:44.764193984+00:00"
sync_method = "copy"
destination_path = "src/userland/cozy"
upstream_tree = "522ef2b10885f66dfa1c6471386df664b78188c4"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "6b464b7fdaebfbcccece67d54adfce54bea844b21f65deddca36bd3252b5ac2f"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
