schema_version = 2
component = "cpython"
repo = "https://github.com/python/cpython.git"
branch = "v3.14.7"
imported_commit = "823f0323ee6ec1402088b73bce1a38473cac36dc"
imported_at_utc = "2026-08-11T15:12:18.387438407+00:00"
sync_method = "copy"
destination_path = "src/development/python/cpython"
upstream_tree = "d046931f9fab3cb94b7179809be4961977819a8b"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d6748ba39050fe8fc828124946f057399918258410aa1601ce3df09350aa5465"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
