schema_version = 2
component = "cryptsetup"
repo = "https://gitlab.com/cryptsetup/cryptsetup.git"
branch = "v2.8.8"
imported_commit = "f1dbcce190719c9e177e8fbaf3df0b908f87d920"
imported_at_utc = "2026-09-18T06:44:42.264691228+00:00"
sync_method = "copy"
destination_path = "src/system/storage/cryptsetup"
upstream_tree = "fb0f145d612c79625155c01feab1c22d50442b10"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b7af5c6c416278c423f777604804b71a6905434964cec8c41af692681dba725c"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
