schema_version = 2
component = "curl"
repo = "https://github.com/curl/curl.git"
branch = "master"
imported_commit = "527573490eb2564b3d7c9dd51d8bff963b5d6303"
imported_at_utc = "2026-08-01T20:43:33.384020526+00:00"
sync_method = "copy"
destination_path = "src/userland/curl"
upstream_tree = "4e6579caa2da9e5ae1363266f5db26fcc0be77b2"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "dc3c85c26ddc0df8f4c5ef333f9fc95465059a2bf665b2b1030300fe05e44a05"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
