schema_version = 2
component = "curl"
repo = "https://github.com/curl/curl.git"
branch = "curl-8_22_0"
imported_commit = "01346829096c61b372692f6dc43ffa778c6caccd"
imported_at_utc = "2026-09-29T01:23:58.735370393+00:00"
sync_method = "copy"
destination_path = "src/userland/curl"
upstream_tree = "6ae23d9333713707a02588b44ed238a50e8b3bde"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "559e9e467d7d053b0d609063a0afcfbb0a4d8df9da3c440ab15218d35d364416"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
