schema_version = 2
component = "dash"
repo = "https://git.kernel.org/pub/scm/utils/dash/dash.git"
branch = "v0.5.13.5"
imported_commit = "037bbdfd330017c368caf6242f977974123239b5"
imported_at_utc = "2026-09-30T00:29:27.704060044+00:00"
sync_method = "copy"
destination_path = "src/userland/dash"
upstream_tree = "a4c44c673810492f94904a8ac0ed3aab97eb385c"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "a192f9159ffad84d5f51315d55cdd8c5a51e76074cefd6f28c44dc89e660181b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-07-17T22:24:14Z"
