schema_version = 2
component = "dbus"
repo = "https://gitlab.freedesktop.org/dbus/dbus.git"
branch = "dbus-1.16.2"
imported_commit = "958bf9db2100553bcd2fe2a854e1ebb42e886054"
imported_at_utc = "2026-08-16T00:38:47.489089024+00:00"
sync_method = "copy"
destination_path = "src/system/dbus/dbus"
upstream_tree = "99b1d4c46226b4fa68cba8ffd7c61e8621147ae1"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "46b315a3cdff69443bd989945cd0f657685a2b544a4d390fdd5d8c2d84f6623d"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
