schema_version = 2
component = "dbus-broker"
repo = "https://github.com/bus1/dbus-broker.git"
branch = "main"
imported_commit = "2956b5d381deeea709c53d02f10e799e50e44f4b"
imported_at_utc = "2026-08-01T22:08:29.075385024+00:00"
sync_method = "copy"
destination_path = "src/system/dbus/dbus-broker"
upstream_tree = "8d613c232f1b4b3f542c1db21203b25f654c4531"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "75988ef72d0d8279adb77afb92b823239145f4722f1b405c9c9ddda96304498e"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/dbus-broker/manifest.toml"
patch_manifest_sha256 = "1a9f560b28f6c224e35f623837aa76b0a502dec8fafe89226e633f4b65094fe1"
