schema_version = 2
component = "dbus-broker"
repo = "https://github.com/bus1/dbus-broker.git"
branch = "main"
imported_commit = "2956b5d381deeea709c53d02f10e799e50e44f4b"
imported_at_utc = "2026-08-01T22:08:29.075385024+00:00"
sync_method = "copy"
destination_path = "src/system/dbus/dbus-broker"
upstream_tree = "8d613c232f1b4b3f542c1db21203b25f654c4531"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "75988ef72d0d8279adb77afb92b823239145f4722f1b405c9c9ddda96304498e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/dbus-broker/manifest.toml"
patch_manifest_sha256 = "e2cfb93f1f76fb9bac2ba4bc15fa71ec1479f6bb155a28e659ff69ad9ee9f313"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-07-02T09:13:39Z"
