schema_version = 2
component = "diffutils"
repo = "https://github.com/uutils/diffutils.git"
branch = "main"
imported_commit = "4e8c5099485af4b15fa0b0221d51a5316ca43ad3"
imported_at_utc = "2026-08-01T00:27:22.412894407+00:00"
sync_method = "copy"
destination_path = "src/userland/diffutils"
upstream_tree = "51ef5d1c205f1d926508685528b9874d88c3c8a5"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "66bf57ef4dd886ad512e5b415effb11f1ac2876761fd53b2612c5a4cabe08486"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
