schema_version = 2
component = "dpkg"
repo = "https://git.dpkg.org/git/dpkg/dpkg.git"
branch = "main"
imported_commit = "ff7e9d8bf01379e8b022028a65afaa262e2c25cd"
imported_at_utc = "2026-08-02T01:52:37.902642936+00:00"
sync_method = "copy"
destination_path = "src/system/packages/dpkg"
upstream_tree = "bedadbc8ef48674fa7cbff090da62050c8f075c5"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b4a579882b351c66ee04b31036a7046a5417d05e71eb59959fb92bc1c490e3ac"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
