schema_version = 2
component = "duktape"
repo = "https://github.com/svaarala/duktape.git"
branch = "v2.7.0"
imported_commit = "03d4d728f8365021de6955c649e6dcd05dcca99f"
imported_at_utc = "2026-08-22T01:30:27.980737210+00:00"
sync_method = "copy"
destination_path = "src/system/security/duktape"
upstream_tree = "07da4088cd7c51ec7d9602bff9201b982883ff02"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "5ce12023f742de768082ca57ddcf8785a81d1401f01074c41df0e5291a712cf9"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
