schema_version = 2
component = "elfutils"
repo = "https://sourceware.org/git/elfutils.git"
branch = "elfutils-0.195"
imported_commit = "302252356da5475670ac5b10dadd091c59689425"
imported_at_utc = "2026-08-03T01:28:46.440908158+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/elfutils"
upstream_tree = "589332c287fe3bfca8c20c7a3edb8b6a8235befb"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "308295d2c3b349811149a2522e4a26af214deeb821c4322025f696364a12345c"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
