schema_version = 2
component = "elisa"
repo = "https://invent.kde.org/multimedia/elisa.git"
branch = "v26.08.1"
imported_commit = "536761f05b603a1763a2c613ae3b5d5f9ddde696"
imported_at_utc = "2026-10-03T00:27:38.747850085+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/elisa"
upstream_tree = "ac0575d7f35b0fc5cf8ebe46a590001395147564"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d53fa92805156a935c8afe5b6351cf5466a905940bab0a2b183cde239ffc593f"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-09-04T20:10:09Z"
