schema_version = 2
component = "expat"
repo = "https://github.com/libexpat/libexpat.git"
branch = "R_2_8_5"
imported_commit = "4b3f0b06f39fb5529cead381694f8929901bc273"
imported_at_utc = "2026-09-29T01:23:25.967211647+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/expat"
upstream_tree = "415519b945a5330f000294e3bd2b7e12a6ffe101"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b5dcd630f229e494669910f6d77953ae0257dd7f6315dafef347b8fda5232994"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
