schema_version = 2
component = "ffmpeg"
repo = "https://github.com/FFmpeg/FFmpeg.git"
branch = "n8.1.2"
imported_commit = "38b88335f99e76ed89ff3c93f877fdefce736c13"
imported_at_utc = "2026-09-18T04:03:49.337753261+00:00"
sync_method = "copy"
destination_path = "src/system/multimedia/ffmpeg"
upstream_tree = "1a0883de7a83dc0b87d0fd89c145a7b4553f1563"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "4b5fd6856f404f334e31c32baf51f88ee025e61d49a92cbbafb317d8cae3c437"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
