schema_version = 2
component = "file"
repo = "https://github.com/file/file.git"
branch = "FILE5_48"
imported_commit = "eb754ace19fed5481d8142426543100a2d6bae4e"
imported_at_utc = "2026-08-11T03:21:39.849205619+00:00"
sync_method = "copy"
destination_path = "src/userland/file"
upstream_tree = "fac768829d3da21345ab927ff294699c1fbc7592"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "68043bedd17dc960dc74d1f9bc4c6e76ef221157cee4f9baad7c496215f26c48"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
