schema_version = 2
component = "fontconfig"
repo = "https://gitlab.freedesktop.org/fontconfig/fontconfig.git"
branch = "2.17.1"
imported_commit = "6d0a98982ec351c165c9224c8b7dbdfca3010e47"
imported_at_utc = "2026-09-17T15:06:17.810505080+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/fontconfig"
upstream_tree = "3d1119a17e51ee9d84d77bb8cb0998968b99a5ce"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "046e416624626c6cd21bddf5e96db0f745e257bbb292cb5d9822b9e88fdf4cd9"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
