schema_version = 2
component = "freetype"
repo = "https://gitlab.freedesktop.org/freetype/freetype.git"
branch = "VER-2-14-3"
imported_commit = "0a0221a1347e2f1e07c395263540026e9a0aa7c7"
imported_at_utc = "2026-08-29T00:23:39.609609754+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/freetype"
upstream_tree = "589225074ab1eb876682820c482069693c251e88"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "34c6d3ef84cf3694a5f0ef8485db7f9ef6c8bda58fb1b254abaca8aef163fde1"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
