schema_version = 2
component = "gcc"
repo = "https://gcc.gnu.org/git/gcc.git"
branch = "releases/gcc-15.3.0"
imported_commit = "4db0e8df15bef836558857c291c323add11d035c"
imported_at_utc = "2026-08-03T17:06:02.372760255+00:00"
sync_method = "copy"
destination_path = "src/toolchain/gcc"
upstream_tree = "0c76aca021168cf1d823c7d3ddc03a3d589d1cff"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "ed26c87b840a6fe015d734b31c96736c46570edbecdc26d395fcfe2648743358"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
