schema_version = 2
component = "gdk-pixbuf"
repo = "https://gitlab.gnome.org/GNOME/gdk-pixbuf.git"
branch = "2.42.12"
imported_commit = "e4315fb8553776e13d39e3f2e0ea8792db61720c"
imported_at_utc = "2026-08-27T22:00:57.431611952+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/gdk-pixbuf"
upstream_tree = "c6b1643638a063f3137b8f688ea08678f91f6f09"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "387311589af3a1c563fe09542fff650f8a7c78cf4fd70f8b9eb218240ef8b526"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
