schema_version = 2
component = "git"
repo = "https://github.com/git/git.git"
branch = "v2.55.0"
imported_commit = "e9019fcafe0040228b8631c30f97ae1adb61bcdc"
imported_at_utc = "2026-08-11T03:21:54.825695513+00:00"
sync_method = "copy"
destination_path = "src/userland/git"
upstream_tree = "31aca3670a1b02adda456bcd92c851dd3e7543cb"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f7b8bccfbc80ab4992771b582055436e206d7e4d520fa9a142660d9f0313b8e7"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "upstream/policies/gitlinks.toml#git"
gitlink_policy = "upstream/policies/gitlinks.toml#git"
patch_manifest = "none"
patch_manifest_sha256 = "none"
