schema_version = 2
component = "glib"
repo = "https://gitlab.gnome.org/GNOME/glib.git"
branch = "2.84.4"
imported_commit = "41eca60845d3fc309af361f5e7f801ba339099aa"
imported_at_utc = "2026-08-16T01:43:00.000000000+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/glib"
upstream_tree = "d533215ffab9fc231be8ddc5767f9fb0712eca95"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "3cc5f72d826dfbb3a8f3d83e37ae134c53613f5e5bd5bdd16fad9d0c63859e4c"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "upstream/policies/gitlinks.toml#glib"
gitlink_policy = "upstream/policies/gitlinks.toml#glib"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
