schema_version = 2
component = "glibc"
repo = "git://sourceware.org/git/glibc.git"
branch = "glibc-2.43"
imported_commit = "f762ccf84f122d1354f103a151cba8bde797d521"
imported_at_utc = "2026-08-03T04:35:46.069681512+00:00"
sync_method = "copy"
destination_path = "src/system/libc/glibc"
upstream_tree = "97ac10e146c65ecbd22d36e3743eb5b5e9166ae9"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "daec62920b0b70f8ee870384c67504514e6669b6c1d7a72362c6f3e3ac90b9f9"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
