schema_version = 2
component = "glib-gvdb"
repo = "https://gitlab.gnome.org/GNOME/gvdb.git"
branch = "main"
imported_commit = "2b42fc75f09dbe1cd1057580b5782b08f2dcb400"
imported_at_utc = "2026-08-16T02:17:00.000000000+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/glib/subprojects/gvdb"
upstream_tree = "29e73de6223f5cd5df2e5ee96f83329e6b691526"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "3a1fcd34f17ea8beeaceda322ce7795403ed3582fc3fb8015421d05c78315c3a"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
