schema_version = 2
component = "gmp"
repo = "https://github.com/gmp-mirror/gmp.git"
branch = "master"
imported_commit = "4b3b66d3328e390af894b97e0438aed90c3305be"
imported_at_utc = "2026-09-18T06:58:54.528927621+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/gmp"
upstream_tree = "0c083fb1e64f2949da637d62f908fb228f5a2140"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "47153ec6a43e04df732e8c5045de0eaaab901f361c1b1f7a2f66d04894010afb"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
