schema_version = 2
component = "gnulib"
repo = "https://git.savannah.gnu.org/git/gnulib.git"
branch = "stable-202301"
imported_commit = "20932856a6a07f056918d58acd09cea4ba150a52"
imported_at_utc = "2026-08-03T20:28:09.302975054+00:00"
sync_method = "copy"
destination_path = "src/build-support/gnulib"
upstream_tree = "7540b9956b5082aa48f2b49f936e7829061b9bc7"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "89b68255a8b6bb6d47426686eb72812f9658ff4c66d5a2a4fbc3c9466bdd7bc2"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
