schema_version = 2
component = "gpgme"
repo = "https://github.com/gpg/gpgme.git"
branch = "gpgme-2.1.2"
imported_commit = "34eaa0a69c120cd1d19365c6b24c58e98cd29cdf"
imported_at_utc = "2026-08-27T22:00:58.921784584+00:00"
sync_method = "copy"
destination_path = "src/system/security/gpgme"
upstream_tree = "6f735dcf713774f592108732f3a2aa5ba6fd5274"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "5e47fb2230d954313a71361de9bce5cf151b02c739977097ae1d7e46c1c551bb"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
