schema_version = 2
component = "greetd"
repo = "https://git.sr.ht/~kennylevinsen/greetd"
branch = "master"
imported_commit = "d6733e983ff7821c3044007d5555345c7553188f"
imported_at_utc = "2026-08-15T23:34:29.865006792+00:00"
sync_method = "copy"
destination_path = "src/system/session/greetd"
upstream_tree = "24b51407a79a72417c3408c07561173a2506144d"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "64ac871a2e08b2e3fc675d1c3a7aa3d6d607807aa42bf9a94773df46065b3d93"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
