schema_version = 2
component = "grep"
repo = "https://github.com/uutils/grep.git"
branch = "main"
imported_commit = "3e5552d8f78a94fb14149a7d3ba3f642725aafb9"
imported_at_utc = "2026-08-01T00:27:16.438468970+00:00"
sync_method = "copy"
destination_path = "src/userland/grep"
upstream_tree = "5eb14f0c3850745017ba81754908a7adb62a9d06"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "68d262ff8998068b19448b442d7dd835abfe3e75178fe34261b2f6ee4c805ac6"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
