schema_version = 2
component = "grub"
repo = "https://gitlab.freedesktop.org/gnu-grub/grub.git"
branch = "grub-2.14"
imported_commit = "d38d6a1a9b79427848976f53d474392cd29c2a71"
imported_at_utc = "2026-09-09T02:09:04.271394773+00:00"
sync_method = "copy"
destination_path = "src/boot/grub/upstream"
upstream_tree = "ffabf807f84ef718fdba560ccc4769f718984754"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "18d00320ca3a7e5fe8c73eed542201cbe4c6b6f79392c5aa29460c0f3a0f4912"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/grub/manifest.toml"
patch_manifest_sha256 = "39dd66d1bd690957162a8fb5c632c0eb642d7df4f1d57f85fb36086a6e65bc9e"
lfs_policy = "none"
lfs_policy_sha256 = "none"
