schema_version = 2
component = "grub-gnulib"
repo = "https://git.savannah.gnu.org/git/gnulib.git"
branch = "master"
imported_commit = "9f48fb992a3d7e96610c4ce8be969cff2d61a01b"
imported_at_utc = "2026-09-09T01:06:26.906997624+00:00"
sync_method = "copy"
destination_path = "src/build-support/grub-gnulib"
upstream_tree = "75f9d6ae709a14d803a402268dc976e4de113934"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "6da9d1d6b5589d1b57c87499e3c3f80a88b4813965a349663a1f6785342b53d1"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
