schema_version = 2
component = "gstreamer"
repo = "https://gitlab.freedesktop.org/gstreamer/gstreamer.git"
branch = "1.26.11"
imported_commit = "e6ee9e63e033b9c8e343ba0bdfa7590ef81449ee"
imported_at_utc = "2026-08-29T00:29:38.141022429+00:00"
sync_method = "copy"
destination_path = "src/system/multimedia/gstreamer"
upstream_tree = "a3ffee970b3ee07a4af9a1db40804606bcf60386"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "ed03206c17f6e9946fd85711da73e70505abf0e5c8864f51cd1f21db35932569"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "upstream/policies/gitlinks.toml#gstreamer"
gitlink_policy = "upstream/policies/gitlinks.toml#gstreamer"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
