schema_version = 2
component = "gzip"
repo = "https://git.savannah.gnu.org/git/gzip.git"
branch = "v1.14"
imported_commit = "fbc4883eb9c304a04623ac506dd5cf5450d055f1"
imported_at_utc = "2026-08-11T03:21:25.517482018+00:00"
sync_method = "copy"
destination_path = "src/userland/gzip"
upstream_tree = "46877741cda7ea91e3ec81329b3c5af3514fc637"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "9db385c18ea143c131b2ce4ef8a9beffa48b3c80d50116f1954931b41fc7f913"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "upstream/policies/gitlinks.toml#gzip"
gitlink_policy = "upstream/policies/gitlinks.toml#gzip"
patch_manifest = "none"
patch_manifest_sha256 = "none"
