schema_version = 2
component = "haruna"
repo = "https://invent.kde.org/multimedia/haruna.git"
branch = "v1.8.1"
imported_commit = "b7278882908338763010eb7bbb93ce4b10fb35f2"
imported_at_utc = "2026-10-03T01:00:25.019486925+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/haruna"
upstream_tree = "f46b80abed2540d9d46fe67e6bddb88e3da811ce"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "e3110670956924b4e4257b9b4228fb5cbd71e4fc5d481918330b6ddd2424871e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-05-19T12:32:38Z"
