schema_version = 2
component = "hwdata"
repo = "https://github.com/vcrhonek/hwdata.git"
branch = "master"
imported_commit = "8bb6c48dc2e683777e625d1c9ef02c1b25b741cd"
imported_at_utc = "2026-08-13T07:31:07.155807948+00:00"
sync_method = "copy"
destination_path = "src/system/data/hwdata"
upstream_tree = "aa0094850e876b8811979182123351d71c0280e6"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "e66e39e904db5f513fbfc58a2ef29612d531f60a2d216e33d57a9c3956156f8f"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
