schema_version = 2
component = "jansson"
repo = "https://github.com/akheron/jansson.git"
branch = "v2.15.1"
imported_commit = "dbb5fb3636e155fccfce4cd215de752779bd6971"
imported_at_utc = "2026-10-03T01:13:39.343321850+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/jansson"
upstream_tree = "42a393f9dd6520fb191d3e301630cdf245d3e504"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "694b829c19741319bfc49d293f564ccd3fd1ce256e73856ffa5c931386a4b7b6"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-07-01T18:35:44Z"
