schema_version = 2
component = "kactivitymanagerd"
repo = "https://invent.kde.org/plasma/kactivitymanagerd.git"
branch = "v6.6.5"
imported_commit = "e0de79231b4315ca688c458e22c531e8b6febfb3"
imported_at_utc = "2026-09-16T02:30:20.585054322+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kactivitymanagerd"
upstream_tree = "cf11628c8e5f2f8753e80d61ce7f474011e38e0a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d748b5c0502b2f48dd9b0e4c4c9464509e5e14104ed42b60f95f2082e80f8cbf"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
