schema_version = 2
component = "karchive"
repo = "https://invent.kde.org/frameworks/karchive.git"
branch = "v6.26.0"
imported_commit = "14a16c7568277389d211b9ded6025e0f400e3dc8"
imported_at_utc = "2026-09-12T22:39:15.874304346+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/karchive"
upstream_tree = "c7dc3ad86f5e1589fa8d57f75cfbc2d533afc440"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d71a6dee553683cf3cf29ba1bf38c7fb685c3c69b418293bef3970100e97788e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
