schema_version = 2
component = "kbookmarks"
repo = "https://github.com/KDE/kbookmarks.git"
branch = "v6.26.0"
imported_commit = "93a31eb7c67ed8ba70b00a5263b77283a2c2202e"
imported_at_utc = "2026-09-13T01:53:59.138878425+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kbookmarks"
upstream_tree = "478c56e99f8421d3eb61218e7e63ad66cb5ad6fc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "818c82a43acbb197cd2d61545a40941b0b6261ca12ec280e682bc2d58652e102"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
