schema_version = 2
component = "kcmutils"
repo = "https://github.com/KDE/kcmutils.git"
branch = "v6.26.0"
imported_commit = "1ffa3b5e5f9de44bb49c8c6a17664c43ee46431d"
imported_at_utc = "2026-09-13T01:20:29.554503643+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kcmutils"
upstream_tree = "9a9b842770cede5b5a36b14aeb9e999dbeab6c10"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "cada13e69efaa87c054010e98895fa655652172d7aa357af92cc91fe1019f050"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
