schema_version = 2
component = "kcodecs"
repo = "https://github.com/KDE/kcodecs.git"
branch = "v6.26.0"
imported_commit = "90bc6c5db860fa715fd4cf2f3b35fb49986fac39"
imported_at_utc = "2026-09-13T02:00:32.241143412+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kcodecs"
upstream_tree = "eec1ce0beedab5230c48d2c1a0c191e1139031c3"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "65315d2944b7de9b7a6862373f8b2074d936033e347798e4a6e2b061f228857e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
