schema_version = 2
component = "kcolorpicker"
repo = "https://github.com/ksnip/kColorPicker.git"
branch = "v0.3.1"
imported_commit = "522e38b61e0786b97b2114c273a4551c869335be"
imported_at_utc = "2026-10-03T00:30:08.147144688+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kcolorpicker"
upstream_tree = "7ada1d456ca7216f038d33e4641ab46febdd134d"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "11dabfddedc78c2f4d1d13765d2311c41df7f7f316eb65fe31127ee3fee9d930"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2024-03-01T15:47:22Z"
