schema_version = 2
component = "kcolorscheme"
repo = "https://invent.kde.org/frameworks/kcolorscheme.git"
branch = "v6.26.0"
imported_commit = "df727793a1673f04f69d51dbbaff0c7915d3896c"
imported_at_utc = "2026-09-12T22:14:42.489653219+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kcolorscheme"
upstream_tree = "4bcba1b499a7aa57b4b8beb4d965593f123b9591"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "292c00d9de4fd8fbbaca9b0555c821b249a63b35a7277064430b7d4932f3f6fe"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
