schema_version = 2
component = "kcompletion"
repo = "https://github.com/KDE/kcompletion.git"
branch = "v6.26.0"
imported_commit = "3bcc8d95c960c71cea26737088b4aae8332547f6"
imported_at_utc = "2026-09-13T01:58:55.414833143+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kcompletion"
upstream_tree = "665188926da76c9d9c3d07757dbbffc1f2b4ce87"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "7a8830fa348d7c8a5832238ac06bc7c2f94db299bc4921d91b3b8bcec099a77f"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
