schema_version = 2
component = "kcoreaddons"
repo = "https://invent.kde.org/frameworks/kcoreaddons.git"
branch = "v6.26.0"
imported_commit = "799c32965cc502ca72815b23e2642f5ba277736d"
imported_at_utc = "2026-09-12T09:02:58.188004835+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kcoreaddons"
upstream_tree = "895b1c0f3c0947080b818c165c7237e1af643431"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "8c330dea96f601a7a14c2718bada831cfedc70d156b1a73a8ef2f185ef014ca4"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
