schema_version = 2
component = "kcrash"
repo = "https://invent.kde.org/frameworks/kcrash.git"
branch = "v6.26.0"
imported_commit = "411aa2ed63a881d5ade82331fbf90f301f3386ce"
imported_at_utc = "2026-09-12T22:14:45.138392639+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kcrash"
upstream_tree = "66e8e8d0315eeadf1f87825ecd617c74da82e81d"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "5b15b65f6a46e372973ef3cdbb9649ac451b82e80ebdfa4aadbd69997e2c32ad"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
