schema_version = 2
component = "kdecoration"
repo = "https://invent.kde.org/plasma/kdecoration.git"
branch = "v6.6.5"
imported_commit = "5a66f51158b0d775baa2bce8b879e0a1d56957b6"
imported_at_utc = "2026-09-12T23:07:51.496149295+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kdecoration"
upstream_tree = "5a82e36162708ad32dd06dcafc6a355defca5607"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "17edcee19bef7029c6b9044b51b489645127c07ad336174004b575e7b78ccc4c"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
