schema_version = 2
component = "kdeclarative"
repo = "https://github.com/KDE/kdeclarative.git"
branch = "v6.26.0"
imported_commit = "23ab14a1e34671956172361ae68fd9d92df90e5f"
imported_at_utc = "2026-09-13T01:20:22.755062009+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kdeclarative"
upstream_tree = "b7abf7f71af9d71d9366bfc31630ce6371dabb4c"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "66794d9c5bd579efbb9a3005afbc57340742ac355149d80744d7e4e3adaf597a"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
