schema_version = 2
component = "kdsingleapplication"
repo = "https://github.com/KDAB/KDSingleApplication.git"
branch = "v1.2.1"
imported_commit = "b63420aebb78df20e37310bb090f075990a5a4f6"
imported_at_utc = "2026-10-03T01:02:16.688223992+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/kdsingleapplication"
upstream_tree = "803b865a0943d31471c68cec2817c9764d965fdc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "e3f816aa512b31398bf5d9104fa3faf3e872e8a2ea7e5fc46c5991d32ba78fae"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-04-22T12:08:26Z"
