schema_version = 2
component = "keyutils"
repo = "https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git"
branch = "v1.6.3"
imported_commit = "cb3bb194cca88211cbfcdde2f10c0f43c3fb8ec3"
imported_at_utc = "2026-09-18T06:44:39.514770133+00:00"
sync_method = "copy"
destination_path = "src/system/security/keyutils"
upstream_tree = "723bc12b41cde925b6c7d0310d5d921d2826edb5"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "123407938665b4838d49e40d13819952d9706e03e97fc0bb978ae2ec0c4da0b3"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
