schema_version = 2
component = "kfilemetadata"
repo = "https://invent.kde.org/frameworks/kfilemetadata.git"
branch = "v6.26.0"
imported_commit = "18349cefb4afcff2714f093408dfdd845e974267"
imported_at_utc = "2026-09-18T00:48:54.851402417+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kfilemetadata"
upstream_tree = "d242d6b587cf36490f103bfff16341708a168741"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "277cb17c60f90ff7bae3d75043250ec166f4be3e5803631d8152a6437381090a"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
