schema_version = 2
component = "kglobalaccel"
repo = "https://invent.kde.org/frameworks/kglobalaccel.git"
branch = "v6.26.0"
imported_commit = "3ee8470c3ac2e060f53fe4c6d7d14fa7ab0304e0"
imported_at_utc = "2026-09-12T22:14:49.666488811+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kglobalaccel"
upstream_tree = "a0473f5aa918503e9a6b705373ba51f8846b833e"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "4255548f0046ff0a0e97d4e63d4234fb117524f6097048e63e778feaca5f9c12"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
