schema_version = 2
component = "kguiaddons"
repo = "https://invent.kde.org/frameworks/kguiaddons.git"
branch = "v6.26.0"
imported_commit = "19d657c78f869258b445f3af74983e470dff46ba"
imported_at_utc = "2026-09-12T22:14:52.393228615+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kguiaddons"
upstream_tree = "96a429ff18eeff2503510966955a1872fb86fdd7"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "461f3cdbf212b0824359e17b648da689dd7ba4858fb973c19bf79d79f05dcee5"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
