schema_version = 2
component = "kholidays"
repo = "https://github.com/KDE/kholidays.git"
branch = "v6.24.0"
imported_commit = "91d1e981338681f861d0171e98b00006bf259b2c"
imported_at_utc = "2026-09-12T23:37:40.442094075+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kholidays"
upstream_tree = "5fc1d1dc13b49ce61591cab9fe508a6324aa1aa6"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "7c7f58c80d37604667b770500ffa3faced1ebbd7772558c92abad23d0a32702d"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
