schema_version = 2
component = "ki18n"
repo = "https://invent.kde.org/frameworks/ki18n.git"
branch = "v6.26.0"
imported_commit = "be6d61539b251ae8f70b64a6528098426dba2af6"
imported_at_utc = "2026-09-12T09:03:10.992108038+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/ki18n"
upstream_tree = "7f8ab71e131ecd3f9d410d13ef940edf0bce2b2f"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "c6cbcbbbbffc0a8e185bd22724071b6889c7130e1a92f53fd6104cff0779540b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
