schema_version = 2
component = "kidletime"
repo = "https://invent.kde.org/frameworks/kidletime.git"
branch = "v6.26.0"
imported_commit = "45ec0921cfe558b686c14c804555f2515b0503ff"
imported_at_utc = "2026-09-12T22:14:54.982703744+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kidletime"
upstream_tree = "23e7dcdaa6ecf7df1af4fbd151f68083bc4efe1d"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "590c121c5294ea5e7c1dec87b8dbcdcaa94785df927b11cb4f65597d4b602b61"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
