schema_version = 2
component = "kimageannotator"
repo = "https://github.com/ksnip/kImageAnnotator.git"
branch = "v0.7.2"
imported_commit = "c481a8936946da6c81cd9042eca3d7aeed8d6982"
imported_at_utc = "2026-10-03T00:44:51.279096393+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kimageannotator"
upstream_tree = "a9c773881b2c067b15a5955d59b3f9ff95795a03"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "3e9f3ceef490a7cff6e9b940c3a7419d1d786edc59ba626b41c0ad921228d48e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2025-11-21T06:31:18Z"
