schema_version = 2
component = "kio"
repo = "https://github.com/KDE/kio.git"
branch = "v6.26.0"
imported_commit = "caf323e0f314ee28b8a9cc1a6cc9fa18a6eeef16"
imported_at_utc = "2026-09-13T01:20:37.737297803+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kio"
upstream_tree = "e944d8cdac5cf92a2bc2aaa7e5df61d8d77304c5"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "7f730e9fb46556c44870152a0111a439be4029d6f2250e837c4855a7dc4b684b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
