schema_version = 2
component = "kirigami-addons"
repo = "https://github.com/KDE/kirigami-addons.git"
branch = "v1.9.0"
imported_commit = "d53b2b24608ae66dbaa4f09d8d7ebae6c9f642b5"
imported_at_utc = "2026-09-17T07:53:38.241396611+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kirigami-addons"
upstream_tree = "ea377f7a051fd54831159dc836d1fd45aa892a7e"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "dba080caef71da555d9dc35fd86c01d5cb5d90c34f6677c5ff8f90afea3e107a"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
