schema_version = 2
component = "kirigami"
repo = "https://invent.kde.org/frameworks/kirigami.git"
branch = "v6.26.0"
imported_commit = "dada4e888b216b297e5c65e44f7a18a95183cbbc"
imported_at_utc = "2026-09-12T22:47:58.004189783+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kirigami"
upstream_tree = "d125748231a2b63dfb541fb352da32289c5e8447"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "aa8b57463cdf7a3e81ed113a8203575d29cf1fdcd6912787720db5ab597d5c35"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
