schema_version = 2
component = "kirigami-addons"
repo = "https://github.com/KDE/kirigami-addons.git"
branch = "v1.15.0"
imported_commit = "4668f4cad74205348f6111e8ef33b5192463fb80"
imported_at_utc = "2026-10-03T02:10:26.734954445+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kirigami-addons"
upstream_tree = "5500fee339f3ed4daa28b895e9e48d8ccb0b10ea"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "8a541c53e5f733c4552ade9e4063991172b9d3f5b0c0b1ee1cb2e385a7f8b00c"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-10-01T01:48:09Z"
