schema_version = 2
component = "kitemviews"
repo = "https://github.com/KDE/kitemviews.git"
branch = "v6.26.0"
imported_commit = "e423e89d213c5cc0a4ab1eb910f2f2d923f2adb2"
imported_at_utc = "2026-09-13T02:06:58.126513340+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kitemviews"
upstream_tree = "ba695e13c873b1dd74c1716b61d137fcd9b9f42d"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f126e8e64785fe50c37619225c536fbab95308c17b8a7c3d62786470d47835f8"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
