schema_version = 2
component = "kjobwidgets"
repo = "https://github.com/KDE/kjobwidgets.git"
branch = "v6.26.0"
imported_commit = "90db0d70c33a918ae580ab6ffe502c6683d6f570"
imported_at_utc = "2026-09-13T02:09:55.218312357+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kjobwidgets"
upstream_tree = "776b812c164c4396fbfdd48d123b3cfae6103ce8"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "dd0b79bbb6e72263e4de73609898b9432e1d0e3ddf03580fc9e8d230147a9d43"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
