schema_version = 2
component = "kmod"
repo = "https://github.com/kmod-project/kmod.git"
branch = "master"
imported_commit = "5086df53090b2fe9fa1c31351c05a78a12a4ba71"
imported_at_utc = "2026-08-01T19:49:29.748556284+00:00"
sync_method = "copy"
destination_path = "src/system/kmod"
upstream_tree = "498c24bfda728e718d7ce7ddb88f224db4a09bd7"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "6f7a3ea937122ac5de989b7aa199f66a30ce8e7ec8583e9ec9252b4c8784f647"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
