schema_version = 2
component = "knewstuff"
repo = "https://github.com/KDE/knewstuff.git"
branch = "v6.26.0"
imported_commit = "3b47aebf3df8e60324921f994bee10f7ff891560"
imported_at_utc = "2026-09-13T01:20:40.808104370+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/knewstuff"
upstream_tree = "b9ff9c72835116df2004a37ea346cf413370de8b"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "033e1e90bd0a8698ae1a5eb1adc6badb9569dd4d71319bc982f0627f0c9d9926"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
