schema_version = 2
component = "knighttime"
repo = "https://invent.kde.org/plasma/knighttime.git"
branch = "v6.6.5"
imported_commit = "1b44543da56e84ab9a39258f13876f021df6093f"
imported_at_utc = "2026-09-12T23:31:09.387475197+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/knighttime"
upstream_tree = "bb53b1c0ea448aa5edad0d7804c21e47a74b9fbb"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "10ed177f034846158a8a8d4b82c5751c6995349b4a093953a29dc0312fd2ec45"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
