schema_version = 2
component = "knotifications"
repo = "https://github.com/KDE/knotifications.git"
branch = "v6.26.0"
imported_commit = "9c3cb2911c88006f844780efda67f5507128491d"
imported_at_utc = "2026-09-13T01:20:44.609153704+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/knotifications"
upstream_tree = "29282af8a501acf125ddda865b8b61f162bfa992"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "8e10e62f2199d0e2c1670a33785d7dc653ccb0fc71f13220a74d5d9693d14fce"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
