schema_version = 2
component = "kpipewire"
repo = "https://invent.kde.org/plasma/kpipewire.git"
branch = "v6.6.5"
imported_commit = "f8ba977dbc4f223aea8372bbe7e73071cd4c2e21"
imported_at_utc = "2026-09-18T00:48:30.845948017+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kpipewire"
upstream_tree = "0944ef0f75dc2b571d0f0dba1e5326440789d967"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "9621b14978ec316a3b200d73e02967f28f5cfa7920d8422c991e3bc8fa254cff"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
