schema_version = 2
component = "kpmcore"
repo = "https://invent.kde.org/system/kpmcore.git"
branch = "v25.12.3"
imported_commit = "b348efa14a9511ec4c0c3c523bb255a910b402d0"
imported_at_utc = "2026-09-11T20:38:04.433628615+00:00"
sync_method = "copy"
destination_path = "src/system/storage/kpmcore"
upstream_tree = "5549e51c5e443226d71158bffdcc7ed6f975fb47"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "49b02f7cb913151d32c63830bd434e259bd957469b5208b73c7bf82b72e775fc"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
