schema_version = 2
component = "kpty"
repo = "https://invent.kde.org/frameworks/kpty.git"
branch = "v6.26.0"
imported_commit = "a88ed97bede73ed6dd7239a29d6f9a23b5f1fd9d"
imported_at_utc = "2026-09-18T00:48:58.684782825+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kpty"
upstream_tree = "7162703bf96c8dee36a9b1d1078b7a4ed16b36bd"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "1eb85cdfbcff6e0f23389560962f18f050489cbb547abb517beaa6a9189f9ecc"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
