schema_version = 2
component = "kquickcharts"
repo = "https://github.com/KDE/kquickcharts.git"
branch = "v6.26.0"
imported_commit = "339e5f19dfbfe89cf69b5ea85f162a657eec7468"
imported_at_utc = "2026-09-17T08:21:49.157588752+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kquickcharts"
upstream_tree = "b56d31d4f21b294b1eb6391057a5aac91ab35c24"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "e02d157fad0910abd884b1d0e35d98bb59a36841e449d95b8a0255d4c2520fa1"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
