schema_version = 2
component = "krunner"
repo = "https://github.com/KDE/krunner.git"
branch = "v6.26.0"
imported_commit = "40908a96309a57299367d2b3b9834c2392f6f4d2"
imported_at_utc = "2026-09-13T01:20:51.910484014+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/krunner"
upstream_tree = "8a4758dd7448fc5f5bf53eac38025cdb883807ba"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "a4b1aee8a679841286e2a436bfdf9f8c7629d09a08dd6ddf3204a795b0c6101b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
