schema_version = 2
component = "kservice"
repo = "https://invent.kde.org/frameworks/kservice.git"
branch = "v6.26.0"
imported_commit = "e422dcdb85b369c04fac849f58e15d788d403eb4"
imported_at_utc = "2026-09-12T22:15:02.603879794+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kservice"
upstream_tree = "871f6d41cfed8be9312bf6e010395cdbd50651ff"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "cc6b5ca8e68da80823f85a8ba51227ef06400d5ecf655b379baef55f15c11c80"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
