schema_version = 2
component = "kstatusnotifieritem"
repo = "https://github.com/KDE/kstatusnotifieritem.git"
branch = "v6.26.0"
imported_commit = "fb56832ebcff866cd817728e86a2f831745ac9f3"
imported_at_utc = "2026-09-13T01:20:53.087127793+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kstatusnotifieritem"
upstream_tree = "24a06f53e251ac1a10212b3bf3d0bf85cf1642be"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "71c0d4ced0b0b3d9f15b18a3a325ef7e84038ad501f124b40b54496444ea4235"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
