schema_version = 2
component = "ksvg"
repo = "https://invent.kde.org/frameworks/ksvg.git"
branch = "v6.26.0"
imported_commit = "fac8d2fc6753e0690ca415a32f0429e44d6a4695"
imported_at_utc = "2026-09-12T22:15:05.146897059+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/ksvg"
upstream_tree = "fc9d6f37790cabd45cc812ed93ff8b8b9c3fc1b4"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "2803f72fb946dd5c5b0d89cc898043bf4388a7dda36d4c186979b6312e401283"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
