schema_version = 2
component = "ksyntaxhighlighting"
repo = "https://invent.kde.org/frameworks/syntax-highlighting.git"
branch = "v6.26.0"
imported_commit = "8a8789ca55c1209109f97a34b18e633c4240bee0"
imported_at_utc = "2026-09-15T20:39:32.024173387+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/ksyntaxhighlighting"
upstream_tree = "dc67a1b948ab8d833af692c092353dcffdd7593c"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "eceeea09e898ee39a87c663eebdb3325d42bb146e03bae50fdaef59bd1f7e139"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
