schema_version = 2
component = "ksysguard"
repo = "https://invent.kde.org/plasma/libksysguard.git"
branch = "v6.6.5"
imported_commit = "7a8874ff0fde7f108a2ed44eb4ef6ec5f28f9064"
imported_at_utc = "2026-09-13T11:06:03.289621460+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/ksysguard"
upstream_tree = "7cca8e280f8bf4195c13c95b22bbbbf18c19ce2c"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f020967bfb2d85f7688f95717b90763eaf50f5e87311ddedab3bb31c61501aae"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
