schema_version = 2
component = "ksystemstats"
repo = "https://invent.kde.org/plasma/ksystemstats.git"
branch = "v6.6.5"
imported_commit = "43527713b7b1ea2ba8412ab44f8beb2f16a2a28e"
imported_at_utc = "2026-09-18T00:48:06.597551774+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/ksystemstats"
upstream_tree = "60802ed5c011bd7a30cfff6508d744bf1af3650a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "8aea5bf7711a8100168f6c62587bfd972e10f906649b5b263f7eb61e798b0684"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
