schema_version = 2
component = "ktextwidgets"
repo = "https://github.com/KDE/ktextwidgets.git"
branch = "v6.26.0"
imported_commit = "2d8f56b0749328924d56a953f8c7717f14bb264a"
imported_at_utc = "2026-09-13T01:20:58.278314162+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/ktextwidgets"
upstream_tree = "64983d6559bb895fd84ca5e09d92f5b9da575de4"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "a13266763180e18636131c23f0ae78c714211d73c3dbc00d3767c69712048a1d"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
