schema_version = 2
component = "ktexteditor"
repo = "https://github.com/KDE/ktexteditor.git"
branch = "v6.26.0"
imported_commit = "163ad01d31c7a7e5190bd9dc7187d91e08bf55c3"
imported_at_utc = "2026-09-13T01:20:56.289222387+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/ktexteditor"
upstream_tree = "6da4ed2677d55e974097c94c989a9ecc537879a3"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "8fb723833819321698433f93ad09c14cc4039f98863918850e023f1dc4ba1d2d"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
