schema_version = 2
component = "kunitconversion"
repo = "https://invent.kde.org/frameworks/kunitconversion.git"
branch = "v6.26.0"
imported_commit = "3d30c3a00260fe0fa70ce1d1889ff41657cc05f5"
imported_at_utc = "2026-09-17T04:19:09.080252864+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kunitconversion"
upstream_tree = "e1b75e78b8cb69b0323f7e2b89ea69298dde186a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "0bb748b1227d0e7632bce57ac1f74da43f4d22de5061c7e3fa8d980b70d7a774"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
