schema_version = 2
component = "kwidgetsaddons"
repo = "https://invent.kde.org/frameworks/kwidgetsaddons.git"
branch = "v6.26.0"
imported_commit = "372bd8fa11769909d5edfd2797ff8059aedf06ab"
imported_at_utc = "2026-09-12T09:03:23.411299267+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kwidgetsaddons"
upstream_tree = "641ecd2c0598dcd7d00cb9b8f5d2e5d7f07618a1"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "a43919d5f818c7bfca1042344a6f131e635cb8a22a343236eaa1cc32a848cc28"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
