schema_version = 2
component = "kwin"
repo = "https://invent.kde.org/plasma/kwin.git"
branch = "v6.6.5"
imported_commit = "b04d59c03749484a8a0ed5a8d4cda515a267c59b"
imported_at_utc = "2026-09-12T19:35:37.194919722+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kwin"
upstream_tree = "99868e7da683d59f3ed90b0f0fe7ebfa4be5bc2b"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "04d5851e100a2ba722021218ca21e62627afc501b0ca277329564b07c21cc4c3"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/kwin/manifest.toml"
patch_manifest_sha256 = "e56ee21b0aa25a30ca042a1cb0d34e17a63b85ec51ba7d424f0406a5e2852c28"
lfs_policy = "none"
lfs_policy_sha256 = "none"
