schema_version = 2
component = "kwindowsystem"
repo = "https://invent.kde.org/frameworks/kwindowsystem.git"
branch = "v6.26.0"
imported_commit = "d701fedb310eacfd17a81e0813580750e0042b93"
imported_at_utc = "2026-09-12T22:15:49.782546315+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/kwindowsystem"
upstream_tree = "ba715f41914b1276bdc4d66d4c97bd74ed15b936"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "648884fed1468e600e0bc47be1809b77c8c6d08ed068461a585b22339e6cf89b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
