schema_version = 2
component = "lcms2"
repo = "https://github.com/mm2/Little-CMS.git"
branch = "lcms2.16"
imported_commit = "453bafeb85b4ef96498866b7a8eadcc74dff9223"
imported_at_utc = "2026-09-12T23:31:04.050205973+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/lcms2"
upstream_tree = "75fc644ec04177c3902e63eee601e0ead2cc3289"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "e2d1d23580289e84587e241155643e5a4d7bca557b18adad176bc7e3e6e26c5e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
