schema_version = 2
component = "libassuan"
repo = "https://github.com/gpg/libassuan.git"
branch = "master"
imported_commit = "92587b7bf5ffbdd34e2139f3563211cd2d04f652"
imported_at_utc = "2026-08-21T21:07:51.914005678+00:00"
sync_method = "copy"
destination_path = "src/system/security/libassuan"
upstream_tree = "1bc682e445cd6c52a63b3db89237f903e87b92d8"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "9009e6aa99217f919687ab910856cf4e99f5ff5b9a5196d5a292c34ffcf055c5"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
