schema_version = 2
component = "libbytesize"
repo = "https://github.com/storaged-project/libbytesize.git"
branch = "2.12"
imported_commit = "518fd4a0a863e896675a7f5ef0164a36eb4d7b03"
imported_at_utc = "2026-09-19T20:59:06.055404141+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libbytesize"
upstream_tree = "8c51d50483e4c20aa6914840dea58628e537500c"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "947a9c78d3e0d2c07a3851572256c228b22c42996138d66231e4d9dc4790a59f"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
