schema_version = 2
component = "libbsd"
repo = "https://gitlab.freedesktop.org/libbsd/libbsd.git"
branch = "0.12.2"
imported_commit = "04a24db27ad1572f766bad772cdd9c146e6d9cf0"
imported_at_utc = "2026-08-02T23:43:22.355661034+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libbsd"
upstream_tree = "d97ec75efa93ffd1ba8cbec5a1a80340934f0676"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "e70592700e62cc3f9980ad3e6ce5cc2ea5ffe895d99d5f92715ba38f6266ebd1"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
