schema_version = 2
component = "libcap"
repo = "https://git.kernel.org/pub/scm/libs/libcap/libcap.git"
branch = "master"
imported_commit = "bd54ca54ff9fc963954f11ffd9acffbaf1447723"
imported_at_utc = "2026-08-02T16:50:31.340583507+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libcap"
upstream_tree = "c144674caf6e4f0c357d6159246228f6823cb453"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "7d50cb90e14f87dd97e04e831e77677169b8e5e247bd90db258a1fb8e1b600c9"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
