schema_version = 2
component = "libcanberra"
repo = "https://github.com/Distrotech/libcanberra.git"
branch = "master"
imported_commit = "edbf1733563f37c650d99fae1e826bf4a46ac3f7"
imported_at_utc = "2026-09-12T23:13:13.502365074+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libcanberra"
upstream_tree = "f71d6bdc0bd852e999b8a068b48d3e39c5b79c97"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "3e802569ce4f5a4bc123bef53f07a09f8807e9a1c5f8d0a91ec750b068f198b4"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
