schema_version = 2
component = "libcosmic"
repo = "https://github.com/pop-os/libcosmic.git"
branch = "master"
imported_commit = "1f8d8786940cc6db59d412153c5a03f69a20375c"
imported_at_utc = "2026-08-12T20:14:33.048606594+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/libcosmic"
upstream_tree = "24378b2d1861e50b1f1908bd8521f9403c409f5c"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "119f76164b2b58eb79ed551bf293c74ac1bf9bb20090ff21fe4e9af7ddb51003"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "upstream/policies/gitlinks.toml#libcosmic"
gitlink_policy = "upstream/policies/gitlinks.toml#libcosmic"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
