schema_version = 2
component = "libdisplay-info"
repo = "https://gitlab.freedesktop.org/emersion/libdisplay-info.git"
branch = "main"
imported_commit = "47a5590e9c4eb35d67651b8c05a55f1a48259329"
imported_at_utc = "2026-08-13T07:29:29.172464084+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libdisplay-info"
upstream_tree = "c594e39bf232a5554e4ecdef423286c995ebfbf2"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "6c99dd12c61dbd7e4f46ec54eaabe8a16e2bc450b4eca00e4c3e52c0e5acd759"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
