schema_version = 2
component = "libdrm"
repo = "https://gitlab.freedesktop.org/mesa/drm.git"
branch = "main"
imported_commit = "523534ee018b01fb93a62d88afca1a41a732c929"
imported_at_utc = "2026-08-13T14:28:54.893061558+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libdrm"
upstream_tree = "0c026f497a7627623c76892b6bad6864b0fb42c4"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "ff5fab7b33f193b89d0feb5ea518b1709a0b06151398a8dc55926ed6b06a59e2"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
