schema_version = 2
component = "libepoxy"
repo = "https://github.com/anholt/libepoxy.git"
branch = "1.5.10"
imported_commit = "c84bc9459357a40e46e2fec0408d04fbdde2c973"
imported_at_utc = "2026-08-29T00:20:38.867835176+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libepoxy"
upstream_tree = "53b90a9e450198734d88acaefd131456cb8458d2"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "065ce65a8fb1c928562242bb724653ad545eb8507e8a766aabdec6eb2cf773c3"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
