schema_version = 2
component = "libfyaml"
repo = "https://github.com/pantoniou/libfyaml.git"
branch = "v0.9.6"
imported_commit = "1ed9bae3b1e5fc57e31a14a2ea12810fdf423473"
imported_at_utc = "2026-08-27T22:12:49.759645646+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libfyaml"
upstream_tree = "eea3c395797d43a0730e501bd028feed661c50bc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f9076838fdc8d9a1b9a6a4f9e0747ab35f05e19e5709248166cd802c3b131b35"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
