schema_version = 2
component = "libglvnd"
repo = "https://github.com/NVIDIA/libglvnd.git"
branch = "v1.7.0"
imported_commit = "faa23f21fc677af5792825dc30cb1ccef4bf33a6"
imported_at_utc = "2026-08-15T18:04:27.629140115+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libglvnd"
upstream_tree = "df07cd3edae472f5036bd6c96144b16b461bd56e"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "693d329bc77b02a6c3c5bf87ba3a2f43952261514d9e6c2f9eed908448090529"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
