schema_version = 2
component = "libgudev"
repo = "https://gitlab.gnome.org/GNOME/libgudev.git"
branch = "238"
imported_commit = "df7c9c9940160307aaeb31347f4776a46f8736a9"
imported_at_utc = "2026-09-18T06:07:25.098556074+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libgudev"
upstream_tree = "691c12228f42d27765bdf6bf2aa65ffdf07370bf"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "18e8607ba70e99b7e3972514fa4ab19eebc29b3b3f1a07ec4217ad5f5824e423"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
