schema_version = 2
component = "libglnx"
repo = "https://gitlab.gnome.org/GNOME/libglnx.git"
branch = "master"
imported_commit = "b415d046880d585e5161bf230590543adeea4fe6"
imported_at_utc = "2026-08-27T21:20:28.494373069+00:00"
sync_method = "copy"
destination_path = "src/system/packages/ostree/libglnx"
upstream_tree = "ec95cf3854fc45fa7a927e5b1cf3ac0c02e52951"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "7652218b673c6e59a27d1d6876b20df47f02cca3d97399aa334b9c29f8240ccd"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
