schema_version = 2
component = "libice"
repo = "https://gitlab.freedesktop.org/xorg/lib/libICE.git"
branch = "libICE-1.1.2"
imported_commit = "adf389fc19aedbf1be077b05365d164cd6f463d8"
imported_at_utc = "2026-09-24T04:31:50.526753622+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libice"
upstream_tree = "cc17fa56fd37c1ce3e31373ad223bb0a2d89ded7"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "5b0f61cf485ed5870ea99ca5a76f27fed359bcb177b604b58dd44a047e094fa6"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
