schema_version = 2
component = "libinput"
repo = "https://gitlab.freedesktop.org/libinput/libinput.git"
branch = "main"
imported_commit = "26191d396d74d505541d6311f0b4ae68d791b890"
imported_at_utc = "2026-08-13T14:28:41.743128036+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libinput"
upstream_tree = "567309b0c5bbb4809d9be44fd8405f01827a6ef8"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "84a5424d5b2bf9051b8aa527aa493ab66057bf5068564b23e741160f5d2a2e89"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
