schema_version = 2
component = "libjpeg-turbo"
repo = "https://github.com/libjpeg-turbo/libjpeg-turbo.git"
branch = "3.2.0"
imported_commit = "c85e6b905bf237038faa936dab160ebfc5da0344"
imported_at_utc = "2026-10-03T00:30:15.225364051+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libjpeg-turbo"
upstream_tree = "d03aadb5488dc9db92c3d62e265ab350109dae87"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "23720cc7756bb36905c8604b79831e86620b69e21085ed8536558615eed227af"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-06-30T17:25:43Z"
