schema_version = 2
component = "libksba"
repo = "https://github.com/gpg/libksba.git"
branch = "master"
imported_commit = "06720f9b16a172404f49089cbb6eb95e4344f562"
imported_at_utc = "2026-08-21T21:07:59.253234539+00:00"
sync_method = "copy"
destination_path = "src/system/security/libksba"
upstream_tree = "44da09ba6a42e9b01ec52395e236795cd960b2ea"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "511c301f8abfb7cc5d955e9b3baf3304fdbb5339f703eb71ec9376e860f2c472"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
