schema_version = 2
component = "libkscreen"
repo = "https://invent.kde.org/plasma/libkscreen.git"
branch = "v6.6.5"
imported_commit = "7545098506d4969e8fc8677b205bd54e3756e3ca"
imported_at_utc = "2026-09-13T10:39:26.907782416+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/libkscreen"
upstream_tree = "a9b55aa2c82296b691ca331a056b22e41f1e990f"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "6afc242723dbce44326055797db3e38f8c3332ec8fb60efd910d4e66c7867a5b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
