schema_version = 2
component = "libmd"
repo = "https://git.hadrons.org/git/libmd.git"
branch = "1.2.0"
imported_commit = "90c4f432134c608c7e2b4dd0a1d7ca5c40b92c7a"
imported_at_utc = "2026-08-02T23:43:19.357661271+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libmd"
upstream_tree = "8995997cfb3e64ffa96bc4b4874aa451c1ba53bc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "2326e47b59a2041c6ef16d84c1657ac8a209642cb3a616ba9a6a92de4bd02c5a"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
