schema_version = 2
component = "libndp"
repo = "https://github.com/jpirko/libndp.git"
branch = "master"
imported_commit = "2730638bf88984b09531813974f9bd14e1a50165"
imported_at_utc = "2026-08-22T02:28:37.734980023+00:00"
sync_method = "copy"
destination_path = "src/system/network/libndp"
upstream_tree = "10eb11dd73557a1b051750a82ed3f1ce2d3b9798"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "5c37a81d8eb0bf00e5c8504a64c12989684752b2bd5399e1a512b85ef238c0d7"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
