schema_version = 2
component = "libpng"
repo = "https://github.com/pnggroup/libpng.git"
branch = "v1.6.58"
imported_commit = "3061454d980de7d53608f594194cfac722721d2a"
imported_at_utc = "2026-08-28T02:47:30.531878041+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libpng"
upstream_tree = "6937cb18b7d1402af72e93af2ef8e9772bb1d2da"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "580c3b9ef2acacd0d655c02cc23dd586cc506f654737b8d4b1d83e70cf7f6fdb"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
