schema_version = 2
component = "libplacebo"
repo = "https://code.videolan.org/videolan/libplacebo.git"
branch = "v7.360.1"
imported_commit = "cee9b076f2c63104ccfd497fa79c39a867293ec4"
imported_at_utc = "2026-10-03T01:03:58.583684288+00:00"
sync_method = "copy"
destination_path = "src/system/multimedia/libplacebo"
upstream_tree = "014a05bfb014d663a244a7e0a5fd4c6f7cc9a849"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "9d937163495fece0d70467e12e1719dc37f5ed7448cee37b5281e572b2780a2c"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "upstream/policies/gitlinks.toml#libplacebo"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-03-13T19:34:27Z"
