schema_version = 2
component = "libtool"
repo = "https://git.savannah.gnu.org/git/libtool.git"
branch = "v2.6.2"
imported_commit = "309bb53a8adfb22c6e5869cc8da049bf123e5438"
imported_at_utc = "2026-09-30T05:52:02.138049310+00:00"
sync_method = "copy"
destination_path = "src/build-tools/libtool"
upstream_tree = "91c1080c7ded7e324bcd92e0614344101b82a681"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "79f12e35e76f0c5d2e43425684ec0017e552c7c71fbeae90c38a9b850489aa59"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "upstream/policies/gitlinks.toml#libtool"
gitlink_policy = "upstream/policies/gitlinks.toml#libtool"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-07-16T15:36:46Z"
