schema_version = 2
component = "libva"
repo = "https://github.com/intel/libva.git"
branch = "2.24.1"
imported_commit = "710eb465c6277ee2cac3e6948767b01eebe7e77a"
imported_at_utc = "2026-09-18T04:03:51.119429248+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libva"
upstream_tree = "bbf3837dfe0cadd987fd6a501554ef55edc94d8a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "6c86ee9a89165332ec5c9979ff6432688b22f8cb366ba86f86a8d242df7e8ebe"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
