schema_version = 2
component = "libxfixes"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxfixes.git"
branch = "libXfixes-6.0.2"
imported_commit = "70d5b0e37f8a759f3dbc218f22954347ceed094a"
imported_at_utc = "2026-09-15T01:50:31.868623865+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libxfixes"
upstream_tree = "6299f720ebb88e5d56a22a2b08a0322681b0a103"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d79c90987ebb300666d30ecf2d4b19b59ce65735fd23c83bf7f90532b2781c04"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
