schema_version = 2
component = "libxrandr"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxrandr.git"
branch = "libXrandr-1.5.5"
imported_commit = "540c3ceef2be3e513b18002a858c7a9591dd749a"
imported_at_utc = "2026-10-03T00:38:50.698156569+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libxrandr"
upstream_tree = "ad52a0137f31fc82635367049f5ac258da0a1a85"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "0aa5507d976791f72e02fc506d1a6e0751530eb71b4ea31901a22bedd9f2f79f"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-01-26T00:14:47Z"
