schema_version = 2
component = "libxtst"
repo = "https://gitlab.freedesktop.org/xorg/lib/libXtst.git"
branch = "libXtst-1.2.5"
imported_commit = "abf3ff74b97c4231d2324d66318bfa1d22e44913"
imported_at_utc = "2026-09-24T04:52:12.381739107+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libxtst"
upstream_tree = "03b2632dfbaf64184b88b5ec6936825dab47df5a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "ffac94ff1289839d6a2721c1ce38c65ab8be8fc77c38ffb46a548e269df6afe1"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
