schema_version = 2
component = "libxcvt"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxcvt.git"
branch = "libxcvt-0.1.3"
imported_commit = "dd8631c61465cc0de5e476c7a98e56528d62b163"
imported_at_utc = "2026-08-29T00:23:09.521420458+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libxcvt"
upstream_tree = "9bf77101f51dce0ec0bf212fc0a650e37c6c1327"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "1129ad167cd65a7c0288fdac203ac2a4de678dc67ea35b4a7ed5f0ad58d8a6fd"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
