schema_version = 2
component = "libxfont"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxfont.git"
branch = "libXfont2-2.0.9"
imported_commit = "975cc6526e892c6fad8fa49d0fef58565fbaa003"
imported_at_utc = "2026-08-29T00:23:31.341465982+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libxfont"
upstream_tree = "915c01c9491ce4586d9a1b6ccde646e013b68fd9"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b9f9480455f38ff652418a2fb564db7098c22bef468d64b55eaa058853c564bc"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
