schema_version = 2
component = "libxext"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxext.git"
branch = "libXext-1.3.6"
imported_commit = "3826a58d190c2d8093d3586cb33867668cbb4553"
imported_at_utc = "2026-08-15T18:21:53.232719772+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libxext"
upstream_tree = "8a4063a884e66c37cf30ba91f32d08daad2f12fc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "06f4cf997729c31136885ea3404d5a23b0646b4ff4a2b5ce0dcb34a898bac78a"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
