schema_version = 2
component = "libxcursor"
repo = "https://gitlab.freedesktop.org/xorg/lib/libXcursor.git"
branch = "libXcursor-1.2.3"
imported_commit = "8ae6cf61b18ecddf26f72a07bbfbd1ea9f022c36"
imported_at_utc = "2026-09-24T05:42:24.875638948+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libxcursor"
upstream_tree = "2ff5fe4e2fcfa100ebfaad1cf776452ddee9a758"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "e1f816e2c78b84415a5439b0e454c72fb81e9646bccc2593a7355cc263201780"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
