schema_version = 2
component = "libxkbfile"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxkbfile.git"
branch = "libxkbfile-1.2.0"
imported_commit = "42e5dedd7fd3c7c73f3870a8751893c03c1afc69"
imported_at_utc = "2026-08-29T00:23:23.989293615+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libxkbfile"
upstream_tree = "8bc77739975c72ea36edc81014642a51c315f222"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "9ce55a44f3fd5b836a5c161f9f8c4ca99a764ed73190ecf26497e6829c915c2b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
