schema_version = 2
component = "libxau"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxau.git"
branch = "libXau-1.0.12"
imported_commit = "a9c65683e68b3a4349afee5d7673b393fb924d2e"
imported_at_utc = "2026-08-15T18:18:52.305686415+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libxau"
upstream_tree = "5fb0355253c32164a0cc4b97992851545a690eac"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "79c163698de210d03d4d8b34cb784cbafab5e915b1a3f6d24dbf03ff405d36f4"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
