schema_version = 2
component = "libxcrypt"
repo = "https://github.com/besser82/libxcrypt.git"
branch = "v4.4.38"
imported_commit = "55ea777e8d567e5e86ffac917c28815ac54cc341"
imported_at_utc = "2026-08-03T02:54:04.192503924+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libxcrypt"
upstream_tree = "57d0673dc1358ce9ede887489c009cebf76a2043"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "5a7a4e391fed152d65aff95f863d90c291bf8cf5b535227a2680fe07a2e21b03"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
