schema_version = 2
component = "libxmlb"
repo = "https://github.com/hughsie/libxmlb.git"
branch = "0.3.29"
imported_commit = "d942cd68a7d78e35b312b9299e69f68f9cd2e503"
imported_at_utc = "2026-08-28T02:14:27.552255433+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libxmlb"
upstream_tree = "cc7abee2404b5eb37d99d608f649ab9a64a48cda"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "c1270ca2bba0184d75a7f7817c40c350d959894912a331b82522fe0c9c0be3f5"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
