schema_version = 2
component = "libxml2"
repo = "https://github.com/GNOME/libxml2.git"
branch = "v2.14.6"
imported_commit = "d23960a130c5bb82779c9405fbbf85e65fb3c57c"
imported_at_utc = "2026-08-27T20:42:10.488824377+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/libxml2"
upstream_tree = "21ba9c1935aea7e68a76963f46cf231a11f991f7"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "41e4f27081dc9524e2970f80bc1dab5e8649d622d4611c33c6bff268f211b70d"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
