schema_version = 2
component = "libx11"
repo = "https://gitlab.freedesktop.org/xorg/lib/libx11.git"
branch = "libX11-1.8.12"
imported_commit = "59917d28a3c41ad22d6fc52e323cafe2cdd596d5"
imported_at_utc = "2026-08-15T18:20:35.065550963+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libx11"
upstream_tree = "9c85a8dbb81500f174e120290989240ed5e4a1ba"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "bdff9d8764f8d127abfe4918260532333418529824f43a7dcc0565bc2149d37b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
