schema_version = 2
component = "libxdmcp"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxdmcp.git"
branch = "libXdmcp-1.1.5"
imported_commit = "1192d3bc407348ff316bd3bffc791b3ac73f591b"
imported_at_utc = "2026-08-15T18:18:55.725588624+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/libxdmcp"
upstream_tree = "35ce39bb0c65e16290426bf9dbf726351275364f"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "45a1f7a21a735385c79b0bf3357e577c8527d927d45b81cc64bfd9638b5cf08f"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
