schema_version = 2
component = "linux-pam"
repo = "https://github.com/linux-pam/linux-pam.git"
branch = "master"
imported_commit = "dd74fc113a9ba1f94d5469f6f7857a1884b3f550"
imported_at_utc = "2026-08-01T01:09:55.279364230+00:00"
sync_method = "copy"
destination_path = "src/system/auth/linux-pam"
upstream_tree = "897ea64339b3da1cc8039360ca69ca3b0c37c263"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "202c2f0889e62c75d1c59a7b66c77ce93fd2f7a115f796ba2617b231e8ce4bb0"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
