schema_version = 2
component = "linux-pam"
repo = "https://github.com/linux-pam/linux-pam.git"
branch = "v1.7.3"
imported_commit = "28fce1fd55b003fec90f34e5bc785e9439b216f2"
imported_at_utc = "2026-09-29T01:23:29.601739784+00:00"
sync_method = "copy"
destination_path = "src/system/auth/linux-pam"
upstream_tree = "1321361b28d20fa69b7a7c34f1c5a32eebb4458f"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "cf767fcc4ba23da46edb85743bc1855bca2012c96ecc31004c13205dcfb5f0f1"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
