schema_version = 2
component = "linux"
repo = "https://github.com/torvalds/linux.git"
branch = "master"
imported_commit = "8ba098e6b6ff0db8edf28528d1552be261af30d4"
imported_at_utc = "2026-08-07T20:46:23.052667136+00:00"
sync_method = "copy"
destination_path = "src/kernel/linux"
upstream_tree = "8ab0cc68986c2725cf993f8cd55ac532c49bc545"
imported_tree_digest_algorithm = "sha256-selected-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "8cd94bc2e634f5738c3b9acd44dae6a0c6cacd90862232e7eb1fa36473255e22"
source_selection_policy = "upstream/policies/linux-source-selection.toml"
source_selection_policy_sha256 = "9dd4e6baf71250d492c77664daefb06870061e509c90d61ddd6c683f4f87400a"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
