schema_version = 2
component = "llvm"
repo = "https://github.com/llvm/llvm-project.git"
branch = "llvmorg-22.1.8"
imported_commit = "ca7933e47d3a3451d81e72ac174dcb5aa28b59d1"
imported_at_utc = "2026-08-11T15:13:40.216523617+00:00"
sync_method = "copy"
destination_path = "src/toolchain/llvm-project"
upstream_tree = "1e4fdb95266974a0cbca9ec4c6f740488322f238"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "5178a0351a1d711b37ee9215df75896daf57835945b3a461cc051fbce98cceb3"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
