schema_version = 2
component = "lvm2"
repo = "https://gitlab.com/lvmteam/lvm2.git"
branch = "v2_03_42"
imported_commit = "56bef2d3430fcc5d5b00f64c099251ea824ad16f"
imported_at_utc = "2026-09-19T21:12:58.263694982+00:00"
sync_method = "copy"
destination_path = "src/system/storage/lvm2"
upstream_tree = "46b6638e16c5bbe6c9ff1468376c9322293ee949"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d4c5285bd1e3cc5eca29d4b83eaa7f223256fb60598a88ce5d10671169b4ee28"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
