schema_version = 2
component = "lz4"
repo = "https://github.com/lz4/lz4.git"
branch = "v1.10.0"
imported_commit = "ebb370ca83af193212df4dcbadcc5d87bc0de2f0"
imported_at_utc = "2026-08-11T20:05:41.116078971+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/lz4"
upstream_tree = "1ff35e0f086e3b431ea0efd001eb5c6254561953"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "11b666d046d340fc86dd55d2370b6df9ab8df66f29674311b5a777db45b35d1b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
