schema_version = 2
component = "m4"
repo = "https://git.savannah.gnu.org/git/m4.git"
branch = "v1.4.21"
imported_commit = "fe2f13ab9ab9b3e712c6529f0b2a49a81feb6ce2"
imported_at_utc = "2026-09-30T05:51:44.682052112+00:00"
sync_method = "copy"
destination_path = "src/build-tools/m4"
upstream_tree = "e766afe6283d970a7af2457b7af1287b39bbbc24"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f8a0f0e1f76c68326b5338d911a9a5d666ea9a68b63ff4f744d1d9fafbe4d8f6"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "upstream/policies/gitlinks.toml#m4"
gitlink_policy = "upstream/policies/gitlinks.toml#m4"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-02-06T19:55:20Z"
