schema_version = 2
component = "material-cursors"
repo = "https://github.com/varlesh/material-cursors.git"
branch = "master"
imported_commit = "2a5f302fefe04678c421473bed636b4d87774b4a"
imported_at_utc = "2026-09-25T00:35:00.439758489+00:00"
sync_method = "copy"
destination_path = "src/desktop/themes/material-cursors"
upstream_tree = "02d64097a616fe9abf01908a9f1079cf18e68afb"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "90fcca5c64f47b38ece9fc2f885cae89fb4e1024a45c216ce5026a9f75844433"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
