schema_version = 2
component = "mesa"
repo = "https://gitlab.freedesktop.org/mesa/mesa.git"
branch = "main"
imported_commit = "e8617e4ca95fc655b0f13fd115c224d27eba2441"
imported_at_utc = "2026-08-13T14:29:21.900787520+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/mesa"
upstream_tree = "18c3ee7cc08c28646d614d75946ba91e577e9fa0"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "44c4b9c23d14b2997a54600d796b1dd0aad920dcf6f7661aa6e30ba8dde81ed1"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
