schema_version = 2
component = "meson"
repo = "https://github.com/mesonbuild/meson.git"
branch = "1.12.1"
imported_commit = "70598bb7825f0f804fb31ec2795de5e79e7692a0"
imported_at_utc = "2026-09-30T05:52:04.297580328+00:00"
sync_method = "copy"
destination_path = "src/build-tools/meson"
upstream_tree = "12297c9f42b7b9232616c432b1fed98948d8a7f0"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "2770b77bccb9b7ef58734c78a600b8e570a0fba1797170f1221ff000b2dee03e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-09-22T21:19:55Z"
