schema_version = 2
component = "milou"
repo = "https://invent.kde.org/plasma/milou.git"
branch = "v6.6.5"
imported_commit = "03565a0e603168d21d7e7a6db9861b28d484d99b"
imported_at_utc = "2026-09-18T00:47:48.322908718+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/milou"
upstream_tree = "969cc2f35d7e223b955a743169ce6b8c5d1bd153"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "03986473e1053abdfacefb4de40aa3061443997245022f6cccec05e4bc0f6290"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
