schema_version = 2
component = "modemmanager-qt"
repo = "https://invent.kde.org/frameworks/modemmanager-qt.git"
branch = "v6.26.0"
imported_commit = "9cada7952c158c5571619cc709475a3bdbe52c98"
imported_at_utc = "2026-09-18T00:49:05.209637029+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/modemmanager-qt"
upstream_tree = "91b9bfe2004046c5fa50a5311acd75a4610c44c1"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "ac948d32a42f7273979fe751ee73e7073e24adf90e8823e6a16f9fd315bbc550"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
