schema_version = 2
component = "mpc"
repo = "https://gitlab.inria.fr/mpc/mpc.git"
branch = "1.4.1"
imported_commit = "532a18ae8222f928c58f7ffd1b4f0122062172bd"
imported_at_utc = "2026-10-02T23:43:06.683440245+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/mpc"
upstream_tree = "d75158c5b04c28423a237579e635d25a72739ff1"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "1da9977efd17428041ef0274c11398cef754703a22e7c18c1819b3ee2dc54b54"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-04-14T12:42:11Z"
