schema_version = 2
component = "mpv"
repo = "https://github.com/mpv-player/mpv.git"
branch = "v0.41.0"
imported_commit = "41f6a645068483470267271e1d09966ca3b9f413"
imported_at_utc = "2026-10-03T01:02:15.408363661+00:00"
sync_method = "copy"
destination_path = "src/system/multimedia/mpv"
upstream_tree = "d0cc1c088a9c72f52d6c232438215c50ceeb11a3"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d112f9290ff67c5e90430beeba542794d1010264738e2d658dc02cf9a2b680c7"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2025-12-21T19:08:20Z"
