schema_version = 2
component = "mpvqt"
repo = "https://invent.kde.org/libraries/mpvqt.git"
branch = "v1.2.0"
imported_commit = "edb1e3213e45aeec7dfcb74b1f5e722264af6636"
imported_at_utc = "2026-10-03T01:00:22.095525079+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/mpvqt"
upstream_tree = "a5dfe441a27f49a3ed4baf556d7364765a99f834"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "880ac112e7db70b5153313da86c93d901ed0535558da82bc433078299b16576a"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-05-18T08:39:00Z"
