schema_version = 2
component = "nasm"
repo = "https://github.com/netwide-assembler/nasm.git"
branch = "nasm-3.02"
imported_commit = "4a56d66ed9626d5a3ded5414c9d8b7f1a48ce065"
imported_at_utc = "2026-10-03T17:30:59.317857291+00:00"
sync_method = "copy"
destination_path = "src/build-tools/nasm"
upstream_tree = "74ef560f33f02ea419bd41b40233e0c9dac62075"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "27424d5f950a78419e1ba250a0f107e0a067dcd3e2c36a70d5890943a7193971"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-06-29T03:37:13Z"
