schema_version = 2
component = "ncurses"
repo = "https://github.com/ThomasDickey/ncurses-snapshots.git"
branch = "master"
imported_commit = "c7556ecbc951326acab37c9cf1e7d690456959e0"
imported_at_utc = "2026-08-01T19:49:33.412577165+00:00"
sync_method = "copy"
destination_path = "src/system/terminal/ncurses"
upstream_tree = "3878425e95b77a29855b13d2858717aca4ed7221"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "1075eb9632607eacded0a0daf649044217e61c8f64906389aa19c4f12cbdc147"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
