schema_version = 2
component = "networkmanager"
repo = "https://github.com/NetworkManager/NetworkManager.git"
branch = "main"
imported_commit = "355bc902994f8f616bc80dcb451455f7aeb6b809"
imported_at_utc = "2026-08-22T01:10:38.188494299+00:00"
sync_method = "copy"
destination_path = "src/system/network/NetworkManager"
upstream_tree = "2cd012a7d0aff2aad6fc38683cde6174e7039841"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "999e0eba5af274de98382308c2ff3f3317500369283137e235b64428f88812d5"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
