schema_version = 2
component = "ninja"
repo = "https://github.com/ninja-build/ninja.git"
branch = "v1.13.2"
imported_commit = "3441b633c2fe2c494e958780ba0f4227b1327634"
imported_at_utc = "2026-09-30T05:52:06.050433518+00:00"
sync_method = "copy"
destination_path = "src/build-tools/ninja"
upstream_tree = "70dd1324a3997a3ce38bfe70a8291b2ef4a0bf65"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f5b3a239aaa2640a08a09a751612b576fa410cd2a2297360eb95b1491d73d747"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2025-11-20T16:26:20Z"
