schema_version = 2
component = "openssl"
repo = "https://github.com/openssl/openssl.git"
branch = "openssl-3.5.7"
imported_commit = "8cf17aaeb4599f8af87fefd810b5b5fee90fe69e"
imported_at_utc = "2026-08-03T01:28:42.648207285+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/openssl"
upstream_tree = "f221bdef224d16f21793595bcf1bc4949bbe7a10"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "76d357aa83a6833d476d02b7cfa4933d1b60dbc6532dda87de5dcdb7044f3f03"
intentional_omission_policy = "upstream/policies/gitlinks.toml#openssl"
gitlink_policy = "upstream/policies/gitlinks.toml#openssl"
patch_manifest = "none"
patch_manifest_sha256 = "none"
