schema_version = 2
component = "openssh"
repo = "https://github.com/openssh/openssh-portable.git"
branch = "V_10_4_P1"
imported_commit = "e8dd756725e8800fcd0b3fd71ee6b4382d1e8fab"
imported_at_utc = "2026-08-11T03:22:04.137666157+00:00"
sync_method = "copy"
destination_path = "src/system/network/openssh-portable"
upstream_tree = "6de1ade940992eb97a1ee4dce7d4be77a7393987"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "766cf32920b333cf07e465b4e9bbe55b5222dd766cba1d6df8291c1361d73ec5"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
