schema_version = 2
component = "opencv"
repo = "https://github.com/opencv/opencv.git"
branch = "4.14.0"
imported_commit = "0654a42e19215ef25b1d367d822f3c630447e7c7"
imported_at_utc = "2026-09-19T21:13:34.413295522+00:00"
sync_method = "copy"
destination_path = "src/system/multimedia/opencv"
upstream_tree = "e8e9bdd74caec3bd791f2da9cbf72498c8d6e21b"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "2a36f58ec87ab204ecd7420a2f02ddfe69d50a4a10a38e586f37d38b603013d4"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
