schema_version = 2
component = "packagekit-qt"
repo = "https://github.com/PackageKit/PackageKit-Qt.git"
branch = "v1.1.4"
imported_commit = "72708dbbe4ae8ca56b9eb4d8dee72cc1ec0534b5"
imported_at_utc = "2026-10-03T01:12:02.901040386+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/packagekit-qt"
upstream_tree = "a05c3b591690234f6657a2718adfc9d5e7c9bc18"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "efe8892a297bf07c18d6ae4da7ed50197a9d2380a18aab114b3e5d314e4e74f2"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2025-10-02T21:10:41Z"
