schema_version = 2
component = "packagekit"
repo = "https://github.com/PackageKit/PackageKit.git"
branch = "v1.4.0"
imported_commit = "16c3c84ab4c498cefe1668314c9efc04e0c172ab"
imported_at_utc = "2026-10-03T01:12:01.831158566+00:00"
sync_method = "copy"
destination_path = "src/system/packages/packagekit"
upstream_tree = "9c051324d1a7bcd4d5664de7bb0b6b3732765596"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "12a6d839d0db07fa6c20ae598967fa2895205e2de72416b0e83e88b6f57f5364"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-09-09T20:42:50Z"
