schema_version = 2
component = "partitionmanager"
repo = "https://invent.kde.org/system/partitionmanager.git"
branch = "v25.12.3"
imported_commit = "6dff98342e66f802de7f0360d32851ded272c068"
imported_at_utc = "2026-10-02T23:48:03.458736113+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/partitionmanager"
upstream_tree = "76c842fe939f06c350dc0a424ae888c12d387db2"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f298bb17585ef9ec101591ee80df939620c44b165a988a893e7fb12314b4a87b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-03-01T03:35:11Z"
