schema_version = 2
component = "patch"
repo = "https://git.savannah.gnu.org/git/patch.git"
branch = "v2.8"
imported_commit = "48ceda8200aaf30c3ce42c31cd70ff6087db2425"
imported_at_utc = "2026-08-11T03:21:35.351136442+00:00"
sync_method = "copy"
destination_path = "src/userland/patch"
upstream_tree = "ce0a306a00a8b4fa9087e7d4e6e1dc7422cc2763"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b3bf0ee4affd29a9afddebeae7ff96c75d2845eb3a71001ae45f37d61f383ed8"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "upstream/policies/gitlinks.toml#patch"
gitlink_policy = "upstream/policies/gitlinks.toml#patch"
patch_manifest = "none"
patch_manifest_sha256 = "none"
