schema_version = 2
component = "paxutils"
repo = "https://git.savannah.gnu.org/git/paxutils.git"
branch = "master"
imported_commit = "481bae11050fcbdca67a66eb57390267b280a312"
imported_at_utc = "2026-08-02T18:27:39.710561301+00:00"
sync_method = "copy"
destination_path = "src/build-support/paxutils"
upstream_tree = "99c4022f1f81352ae2b85174c58c17c722f48163"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "46a27afc841633d719120d652d81c777366645349b6a4848ff04a624efcceab4"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
