schema_version = 2
component = "pcre2"
repo = "https://github.com/PCRE2Project/pcre2.git"
branch = "pcre2-10.49"
imported_commit = "6f9d7c1373262c541324a16a358785b33ef116cf"
imported_at_utc = "2026-09-29T01:23:27.959052869+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/pcre2"
upstream_tree = "f5a1495b9e14d7941757b8c76afab2a28b9da0e6"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "64815309b7cf38022ec6804f61d9a19c3f7592a8ff2b6b9d9792aa22b8b6395e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "upstream/policies/gitlinks.toml#pcre2"
gitlink_policy = "upstream/policies/gitlinks.toml#pcre2"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
