schema_version = 2
component = "perl"
repo = "https://github.com/Perl/perl5.git"
branch = "v5.44.0"
imported_commit = "e634cc838fb1785dfafb5d13b52807ea16b5c52c"
imported_at_utc = "2026-09-30T05:52:12.260520219+00:00"
sync_method = "copy"
destination_path = "src/development/perl"
upstream_tree = "859e2bb49066e8dc2cbb31c84bcc49eb363f6403"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "932ca9031460d68aa055c0771b1f90a25ad60f38a989b6d91f72830d9a4dcdfa"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-07-13T15:18:45Z"
