schema_version = 2
component = "pixman"
repo = "https://gitlab.freedesktop.org/pixman/pixman.git"
branch = "master"
imported_commit = "9cc163c9da0fb4da430641715313d95a6ec466d9"
imported_at_utc = "2026-08-13T14:28:47.771695915+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/pixman"
upstream_tree = "8b8f70a2168447b445f51469426bf929514b7212"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "40c922d13e7f5775dc5993e1d521de964624527aaf8912d8f11a78834112d8ba"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
