schema_version = 2
component = "pkgconf"
repo = "https://github.com/pkgconf/pkgconf.git"
branch = "pkgconf-3.0.7"
imported_commit = "0c9e506b64124d8727b68d8af0ed73739e66e2ba"
imported_at_utc = "2026-09-30T00:30:16.394709617+00:00"
sync_method = "copy"
destination_path = "src/build-tools/pkgconf"
upstream_tree = "04b10eb575655dfad7b31190fee394b4779e1b7e"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "126a48ee777d5ff2b7fa5bbcf3539c5fa9d519e77afebc60213c9978afe16e12"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-09-04T20:51:54Z"
