schema_version = 2
component = "plasma-systemmonitor"
repo = "https://invent.kde.org/plasma/plasma-systemmonitor.git"
branch = "v6.6.5"
imported_commit = "ec32a4e2ecd9f43486bc679ad586b691e4bdcb29"
imported_at_utc = "2026-09-18T00:48:03.513304346+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/plasma-systemmonitor"
upstream_tree = "172a2b4a2028adb569949b22e549e06f66d7cac4"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "506577fd5c995837d908d01b8d2fcd657b7006418f4a426e58df7f23b76d2548"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
