schema_version = 2
component = "plasma-pa"
repo = "https://invent.kde.org/plasma/plasma-pa.git"
branch = "v6.6.5"
imported_commit = "a6c6c75885b004f81a24d1fc58c5bd793be05266"
imported_at_utc = "2026-09-18T00:48:13.744089996+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/plasma-pa"
upstream_tree = "1e7bdb49c7967d12ed90f14dad4d8417571fb375"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "bebc96cc5ddd98431651740a76131fe6904072a205c848086e3c05ef8475dafd"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
