schema_version = 2
component = "plasma-login-manager"
repo = "https://invent.kde.org/plasma/plasma-login-manager.git"
branch = "v6.6.5"
imported_commit = "fc429687709b8b32f2cb41437b6b31bb8e9c78c4"
imported_at_utc = "2026-09-23T19:04:28.836872803+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/plasma-login-manager"
upstream_tree = "bc0bfa0a0113a2eb3f638299406a3942c19fa0a9"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "73907b7ab7fa729d29f743be865c83823fca0aa9f42c4a51511c5e9c178e56b7"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
