schema_version = 2
component = "plasma-wayland-protocols"
repo = "https://invent.kde.org/libraries/plasma-wayland-protocols.git"
branch = "v1.20.0"
imported_commit = "6fee13b7c0b25d4619e20090f4a178fc2b460be7"
imported_at_utc = "2026-09-12T22:20:49.795436099+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/plasma-wayland-protocols"
upstream_tree = "f54cfd1fdcbcf9535fe266a244bd64f4ad07891b"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "59dc88bf72cc912a2a2b98a49087c4558742f777f3bc2157fb9d78b5f6ef0c92"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
