schema_version = 2
component = "plasma-workspace"
repo = "https://invent.kde.org/plasma/plasma-workspace.git"
branch = "v6.6.5"
imported_commit = "28245c69a5aea1dc11d44f75616b86b04a7fb2aa"
imported_at_utc = "2026-09-12T19:35:50.638361402+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/plasma-workspace"
upstream_tree = "8794e4f72203ada2ebc4f4f38e1741a5b9c14ba2"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "13dea8651d5506745e5a5c306712b8636de65662e079f4bb015cc9d056da7035"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
