schema_version = 2
component = "plasma-activities-stats"
repo = "https://invent.kde.org/plasma/plasma-activities-stats.git"
branch = "v6.6.5"
imported_commit = "ec88220621c2b2df85d633519f68b34f1b65f981"
imported_at_utc = "2026-09-13T10:34:42.598221556+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/plasma-activities-stats"
upstream_tree = "ea11601b47c694d98d17eaf4744997b056a7cd9b"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "73b85620f7bd15ec83e582dab072a07cea6deda6451be276bf618e1c32bfc114"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
