schema_version = 2
component = "plasma-activities"
repo = "https://invent.kde.org/plasma/plasma-activities.git"
branch = "v6.6.5"
imported_commit = "144e52b0a5c48b367bbcee87f126fd6cdd3d308e"
imported_at_utc = "2026-09-13T10:04:18.430133422+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/plasma-activities"
upstream_tree = "62b4005f109f394a7634254c5974cac8c526e93a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "4d1c1008e979c1f73db1e9efd2d798ebd6dc9523b802a988c4bd48ec9e1a9a98"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
