schema_version = 2
component = "plasma5support"
repo = "https://invent.kde.org/plasma/plasma5support.git"
branch = "v6.6.5"
imported_commit = "29d9fd23306bc5b90332bd98cde238ffb19ed830"
imported_at_utc = "2026-09-17T04:11:33.623435634+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/plasma5support"
upstream_tree = "252b98370e4a370a9e5092de6b412e8b88b722cb"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "67cc80ee9cd7ec4a29eafd62fc4ab7bff65d376bc7a0bcec44c01cc28edf269d"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
