schema_version = 2
component = "polkit"
repo = "https://github.com/polkit-org/polkit.git"
branch = "main"
imported_commit = "6f3cec7f1cfd2b0a686ce53e97e5351c80fe4f32"
imported_at_utc = "2026-08-22T01:13:13.877581101+00:00"
sync_method = "copy"
destination_path = "src/system/security/polkit"
upstream_tree = "19b1b760d5470cc7404083d9fca303505d8dc5ba"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "008dade0125d7c3e70d5e599d24ac236d507a671e239fb9177041859b3b98072"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
