schema_version = 2
component = "polkit-qt-1"
repo = "https://invent.kde.org/libraries/polkit-qt-1.git"
branch = "v0.200.0"
imported_commit = "aa1c6c414ec021fd32e30492c00bb13347e228db"
imported_at_utc = "2026-09-11T20:38:01.281930913+00:00"
sync_method = "copy"
destination_path = "src/system/security/polkit-qt-1"
upstream_tree = "5664f661ebc63c823b98446c0a9b869e4a95fb5a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "29c5f69cc5d49eac6ca7554c232763d976c2bc47ed440836ec16eecb723875db"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
