schema_version = 2
component = "polkit-kde-agent-1"
repo = "https://invent.kde.org/plasma/polkit-kde-agent-1.git"
branch = "v6.6.5"
imported_commit = "cc47555bf1b989903a8421ad666fd0270feb4d78"
imported_at_utc = "2026-09-18T00:48:21.932334311+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/polkit-kde-agent-1"
upstream_tree = "7dacdad7e56ccbf77f68a18522b378c534e17512"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f9fbfe73367da5b4f55f38ecf1bd48e89fbafa3e58ba5a5c8beeb6597ccd0e70"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
