schema_version = 2
component = "pop-fonts"
repo = "https://github.com/pop-os/fonts.git"
branch = "master"
imported_commit = "2da23d5e76bf724c49875e8fd328e1fd5a6de80e"
imported_at_utc = "2026-08-16T01:29:28.525743126+00:00"
sync_method = "copy"
destination_path = "src/desktop/fonts/pop-fonts"
upstream_tree = "3ad41e083b8a36cd678bebe2db5b5ecaed7575b9"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "3585404870d6735d36238637eddabc9014e1d6b01ba7757ed60aad079565052b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
