schema_version = 2
component = "pop-icon-theme"
repo = "https://github.com/pop-os/icon-theme.git"
branch = "master"
imported_commit = "1a575a8e99b4ae629b9b16543a3a04d148632ba9"
imported_at_utc = "2026-08-15T23:37:12.235422220+00:00"
sync_method = "copy"
destination_path = "src/desktop/themes/pop-icon-theme"
upstream_tree = "3cc7142d018b5c3a6f8e466736a95b31c4c305b6"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "ad08b529d4cdb90e672399b3130ec3b9098260de730f6a5074e65c0e8abe1feb"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
