schema_version = 2
component = "power-profiles-daemon"
repo = "https://gitlab.freedesktop.org/upower/power-profiles-daemon.git"
branch = "0.30"
imported_commit = "5b4994c8a91290481bef87a5bae95391d0ec677f"
imported_at_utc = "2026-09-18T05:03:42.989854033+00:00"
sync_method = "copy"
destination_path = "src/system/services/power-profiles-daemon"
upstream_tree = "8310d18187f51b027004b3fc3e35f2bdd1ef5840"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "55d2f94e31073e9f70e8653ef8d923ea574f2ec07989cd18809407c6a385f9d8"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
