schema_version = 2
component = "prison"
repo = "https://github.com/KDE/prison.git"
branch = "v6.26.0"
imported_commit = "5f8346bd9dd244a6dc2541cf906d129be4dbc2c5"
imported_at_utc = "2026-09-13T01:20:50.653240548+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/prison"
upstream_tree = "9355cbbfb7d4c2fa965d4795187c252cf6e46c17"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "0b4345ce6e9b79ec686c594887fef84ee7b2321786f02181bbffe4ff8cada197"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
