schema_version = 2
component = "pulseaudio-qt"
repo = "https://invent.kde.org/libraries/pulseaudio-qt.git"
branch = "v1.9.0"
imported_commit = "7ec54e778fcaefadb4c62da142e536d1d7346803"
imported_at_utc = "2026-09-18T00:49:11.037205059+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/pulseaudio-qt"
upstream_tree = "67bb9f69781753ebcb85a6d7f4969c00a28a0141"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "0b2d69266a6b390892aa1c7ced2d0a1e5aed39bfe298b9cfd01762f92a669179"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
