schema_version = 2
component = "purpose"
repo = "https://invent.kde.org/frameworks/purpose.git"
branch = "v6.26.0"
imported_commit = "2976526a14272a45409d7562465f00f58a215d89"
imported_at_utc = "2026-09-18T00:49:08.411924730+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/purpose"
upstream_tree = "bd0c7fa6b176d580045930ce16cefde501530907"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "49465904855325cf30e9a951e89959827dacebc549b15329742732d595edba99"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
