schema_version = 2
component = "qca"
repo = "https://invent.kde.org/libraries/qca.git"
branch = "v2.3.12"
imported_commit = "c7de7c95043b7af1846cd55058474cff4508bb6c"
imported_at_utc = "2026-09-15T21:02:16.229849430+00:00"
sync_method = "copy"
destination_path = "src/system/security/qca"
upstream_tree = "5517905823bc8019046d175a1416a287488aed8c"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "60adf5d8896a4c1923fe1b2a61e51440ac2cc8ca70dfec0efb98beb025438a9b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
