schema_version = 2
component = "qqc2-desktop-style"
repo = "https://invent.kde.org/frameworks/qqc2-desktop-style.git"
branch = "v6.26.0"
imported_commit = "a63714aa1b59d8c1b0639bab3da5063eabcfcaf8"
imported_at_utc = "2026-09-18T22:51:20.556858912+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/qqc2-desktop-style"
upstream_tree = "50c53f10522c9a03a318379501c18621b1c0e4a6"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "0e77c426d6aed0e6c321c76fa8fd2be74d93e531d4b054e46836ceb4862e9b7b"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
