schema_version = 2
component = "qt5compat"
repo = "https://code.qt.io/qt/qt5compat.git"
branch = "v6.11.2"
imported_commit = "abebcdb4964aa1f9ca01b97d793ed57d305d2a66"
imported_at_utc = "2026-09-12T21:29:52.939020254+00:00"
sync_method = "copy"
destination_path = "src/desktop/qt/qt5compat"
upstream_tree = "ba4721bbb62832c86ad57ae6b57cfa734daf4c65"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b3a4440140c48e0e4fb470bad0c82e063b5837943a10b045a23382db8f15c2ae"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
