schema_version = 2
component = "qtbase"
repo = "https://code.qt.io/qt/qtbase.git"
branch = "v6.11.2"
imported_commit = "ef55f427f2c8b410d34f8a7681020a3000cf6866"
imported_at_utc = "2026-09-11T21:11:37.078239730+00:00"
sync_method = "copy"
destination_path = "src/desktop/qt/qtbase"
upstream_tree = "e414f40795dfc79c4a13e0c03ce37b2145ed33be"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "5f864733362dd3bdef896eb88de564868e594f1a18d8c2d16009507ba12c06e3"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
