schema_version = 2
component = "qtlocation"
repo = "https://github.com/qt/qtlocation.git"
branch = "v6.11.2"
imported_commit = "709ecccbd647ffa25545e0886be59001d0266e88"
imported_at_utc = "2026-09-13T00:21:47.464936631+00:00"
sync_method = "copy"
destination_path = "src/desktop/qt/qtlocation"
upstream_tree = "eb3de840220869aa771edd7d992e472b6fc6a21e"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "9767ae9b56f18370e6eaa6b3b3d830e1386467bfba83d84a55ea1b5ad6707f30"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
