schema_version = 2
component = "qtmultimedia"
repo = "https://code.qt.io/qt/qtmultimedia.git"
branch = "v6.11.2"
imported_commit = "6f162ccac1425edbd7b4d1582fabab5973b43d6c"
imported_at_utc = "2026-09-20T00:07:01.713931260+00:00"
sync_method = "copy"
destination_path = "src/desktop/qt/qtmultimedia"
upstream_tree = "5219d3f276968bfb151f74a1214f874fa3d7447f"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "e254bf8ae7155e5f13177e788320ea420b94219b5f9f809720b3a560c43808eb"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
