schema_version = 2
component = "qtpositioning"
repo = "https://github.com/qt/qtpositioning.git"
branch = "v6.11.2"
imported_commit = "f68ed52ba071c8c7030810ee91fdd186b7d9d9f7"
imported_at_utc = "2026-09-26T01:46:40.852756466+00:00"
sync_method = "copy"
destination_path = "src/desktop/qt/qtpositioning"
upstream_tree = "0a051a1e3ffa5c217f1b310d8483b4c2606691d5"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "be4a4d9c1a6135395936cfc8101c28863ba2cfbcddf806a2f340a047d1e2594e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
