schema_version = 2
component = "qtpositioning"
repo = "https://github.com/qt/qtpositioning.git"
branch = "v6.11.2"
imported_commit = "f68ed52ba071c8c7030810ee91fdd186b7d9d9f7"
imported_at_utc = "2026-09-12T23:44:56.470039585+00:00"
sync_method = "copy"
destination_path = "src/desktop/qt/qtpositioning"
upstream_tree = "0a051a1e3ffa5c217f1b310d8483b4c2606691d5"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "354362fc1e80f526afcfb59e5ca0500a951eb43dafa553e9f1fad04fa804a2cc"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
