schema_version = 2
component = "qtshadertools"
repo = "https://code.qt.io/qt/qtshadertools.git"
branch = "v6.11.2"
imported_commit = "c70b59ea4a47ccbee7e0d0353b9e91d719120bfd"
imported_at_utc = "2026-09-12T07:51:15.813204610+00:00"
sync_method = "copy"
destination_path = "src/desktop/qt/qtshadertools"
upstream_tree = "bbe095f7ce3035815fcefc969d00178732a376bc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "c80a71ceb8a991faa6fc59fda514d6f8af3ff67c775cd903ab0befb635532934"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
