schema_version = 2
component = "qtspeech"
repo = "https://code.qt.io/qt/qtspeech.git"
branch = "v6.11.2"
imported_commit = "ae2de454bc73956632841221c535959f6f950346"
imported_at_utc = "2026-09-15T20:21:23.074546168+00:00"
sync_method = "copy"
destination_path = "src/desktop/qt/qtspeech"
upstream_tree = "9a9c7be1052caca525a2f1cc07977a1512aa21a8"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "6c8b96fdc602ce5343fc02564a628e1eeb004acf86ef7c7a42c76161f43110cb"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
