schema_version = 2
component = "qtsvg"
repo = "https://code.qt.io/qt/qtsvg.git"
branch = "v6.11.2"
imported_commit = "17ca512f903f935282ebeca496aac5d11ba4199a"
imported_at_utc = "2026-09-11T21:11:42.688108518+00:00"
sync_method = "copy"
destination_path = "src/desktop/qt/qtsvg"
upstream_tree = "bc11fdd8ad0c6e5b7987048ccd3ba4a987b7d94a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "ca3cca321941c5173b9f6ea9765e49e28ea42fa39eca39eff70ac271f2306d11"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
