schema_version = 2
component = "qtwayland"
repo = "https://code.qt.io/qt/qtwayland.git"
branch = "v6.11.2"
imported_commit = "fd0456558bc1766da85aee42f6a87f79092cbb13"
imported_at_utc = "2026-09-11T21:11:48.765292347+00:00"
sync_method = "copy"
destination_path = "src/desktop/qt/qtwayland"
upstream_tree = "55c21afd874d9c27961adba5577d501acc1fd3e0"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "4a929a475ef813d49829abb41f192922b994aa9c775966efcf6eddd114dddf48"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
