schema_version = 2
component = "rsync"
repo = "https://github.com/RsyncProject/rsync.git"
branch = "v3.5.1"
imported_commit = "04355d27b7386d7de0e6bd5e79c556223210f700"
imported_at_utc = "2026-09-30T00:29:59.124310598+00:00"
sync_method = "copy"
destination_path = "src/userland/rsync"
upstream_tree = "a879164ac3785694e28f191dcfbf921ec498cc6f"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "5bc34d191aaa24476810ee3175a4926a3703654868f8343259aea34e1c6089d5"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-09-21T03:41:01Z"
