schema_version = 2
component = "seatd"
repo = "https://github.com/kennylevinsen/seatd.git"
branch = "master"
imported_commit = "daa8196e10b180b8b0caeafa8e5f860eb1bd6706"
imported_at_utc = "2026-08-13T07:28:24.297231867+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/seatd"
upstream_tree = "887faf1a01a454425008a1c77aabb524a511b7d3"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "35b59a8ae2781e4e71402f45d1fe5ab072ee39e2d1fd2109b32d00d74b498b2e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
