schema_version = 2
component = "sed"
repo = "https://github.com/uutils/sed.git"
branch = "main"
imported_commit = "7239fb0e08d7d3ba2742ecc3c28f0d0e3eb5a4dd"
imported_at_utc = "2026-08-01T00:27:18.507072425+00:00"
sync_method = "copy"
destination_path = "src/userland/sed"
upstream_tree = "239067c934e645dab81bd63275e8b5e6d020a4cc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f64f06a13bac952708beeb413b80d4107fb05d6ccf660089c95862a52d4a6281"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
