schema_version = 2
component = "sed"
repo = "https://git.savannah.gnu.org/git/sed.git"
branch = "v4.10"
imported_commit = "89b7a2224d4faa9d8baf76094b1232ad1477ef3e"
imported_at_utc = "2026-09-30T00:29:11.957827142+00:00"
sync_method = "copy"
destination_path = "src/userland/sed"
upstream_tree = "c936553457fbe39c839e077c6fa68dc37ac51c30"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "0b884d095f59b0fa3ec61287dac3c7a0816c9dfdbdc4125010b51ef77fc8f4de"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "upstream/policies/gitlinks.toml#sed"
gitlink_policy = "upstream/policies/gitlinks.toml#sed"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-04-22T01:32:56Z"
