schema_version = 2
component = "shadow"
repo = "https://github.com/shadow-maint/shadow.git"
branch = "master"
imported_commit = "855d15a04625818fa28a94e693dd4dc7acfb5af3"
imported_at_utc = "2026-08-01T01:09:58.249206763+00:00"
sync_method = "copy"
destination_path = "src/system/auth/shadow"
upstream_tree = "67efa9af3ede661085113cb1ada220ecd00ac24b"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "bead9a79d06d1e15acae82485f19bc47eb0364a842a23283673d2b2bde36a456"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
