schema_version = 2
component = "shared-mime-info"
repo = "https://gitlab.freedesktop.org/xdg/shared-mime-info.git"
branch = "2.5.1"
imported_commit = "fd8ab89c20093f1bfba8fa9e302ba584fffd0fd7"
imported_at_utc = "2026-10-02T18:15:41.370186867+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/shared-mime-info"
upstream_tree = "d9d08b3d38592dcd2508f6b8a5521bb501596d78"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "38bec8cefb4b0ae09bbf3846de00cca86f8e9d482bb1ee010db37eea669ffed5"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-06-29T15:04:47Z"
