schema_version = 2
component = "slate"
repo = "https://github.com/HungLo2020/Slate.git"
branch = "main"
imported_commit = "32df63dc111cf923db37668c48e142b1777f26ba"
imported_at_utc = "2026-10-09T20:11:10.672107480+00:00"
sync_method = "copy"
destination_path = "src/userland/slate"
upstream_tree = "78cd13026520f0f9b0a7c4b1e419aa6896de5dbc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "802d0bdec9f153d9e8db87086f9795e35f8961f4ba56711f30da9875d98a6d18"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
upstream_committed_at_utc = "2026-10-09T19:00:02Z"
