schema_version = 2
component = "sljit"
repo = "https://github.com/zherczeg/sljit.git"
branch = "master"
imported_commit = "45f910b78c6605ebf5b53d3ec7cb00f2312fe417"
imported_at_utc = "2026-08-03T03:05:26.910551083+00:00"
sync_method = "copy"
destination_path = "src/build-support/sljit"
upstream_tree = "132463bc0593e0c05fd92fd993a5e4a2dd415df3"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "28e843984d5e60f12e05184eb4e527ced6bde0043cee6145ab7d88bf5806527b"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
