schema_version = 2
component = "sljit"
repo = "https://github.com/zherczeg/sljit.git"
branch = "master"
imported_commit = "de0259c7aaf36aa40cba8014f3fad3edde9307f9"
imported_at_utc = "2026-09-29T01:25:07.163039178+00:00"
sync_method = "copy"
destination_path = "src/build-support/sljit"
upstream_tree = "ff08222651decac5fe46a13bb90cb5efb8d9765e"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "e599194d583f8084b97624e5b4649b628a72386845297a6ee6e582fca34aca3d"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
