schema_version = 2
component = "solid"
repo = "https://github.com/KDE/solid.git"
branch = "v6.26.0"
imported_commit = "f4ee22958f3a6feee71eda3f8d63347c74c886c0"
imported_at_utc = "2026-09-13T01:43:01.754749960+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/solid"
upstream_tree = "7cc5c2f0fe0a83f3f0a935c18eb403739a71d719"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "6530092ae8554d7824e86b221707a35f222f1be47545fd836ed027eae98f5dce"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
