schema_version = 2
component = "sonnet"
repo = "https://invent.kde.org/frameworks/sonnet.git"
branch = "v6.26.0"
imported_commit = "331e7290fa41e116ffa2e3afdf797fe9173aea39"
imported_at_utc = "2026-09-13T06:51:55.519907921+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/sonnet"
upstream_tree = "91a367d58ef0f57ce1f3c2241cf26f4d0ccbf452"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d321c969513ffa57aa26a3ad537c9b0a7c4d24e33b381a52b461720e51f4c8f2"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
