schema_version = 2
component = "spectacle"
repo = "https://invent.kde.org/graphics/spectacle.git"
branch = "v6.6.5"
imported_commit = "37b33707dc5b5eb3c82c477d6afee13e606b2c19"
imported_at_utc = "2026-09-18T00:48:51.701304282+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/spectacle"
upstream_tree = "dbeb6a94a3a72375bce52e3a78964d5e23a29245"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "38ebf0384303faf76ee4beab757f62ef74cf6a23a67fe571abbfac7042c8ff58"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
