schema_version = 2
component = "sudo-rs"
repo = "https://github.com/trifectatechfoundation/sudo-rs.git"
branch = "main"
imported_commit = "e5a01fd7a20a5bfe5da6bc1b5cf7628e721c35c8"
imported_at_utc = "2026-08-01T01:09:59.765052601+00:00"
sync_method = "copy"
destination_path = "src/system/auth/sudo-rs"
upstream_tree = "f45cebb508d82b19697eb31dee13a47ffdbcc641"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "942d461863e964f50717efe8e135b0ccd9d6b2f6e33609e440e9fad1fb48d46b"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
