schema_version = 2
component = "sudo-rs"
repo = "https://github.com/trifectatechfoundation/sudo-rs.git"
branch = "v0.2.15"
imported_commit = "e4cfa9cf7b71e287dd5046633c0f5276072d147d"
imported_at_utc = "2026-09-29T01:23:31.017980708+00:00"
sync_method = "copy"
destination_path = "src/system/auth/sudo-rs"
upstream_tree = "9fbe961ff6de140bc5812e675f8f8852e4878ea1"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "31a2a4e1c49b5182900f7c95a1e72b001360f17f52bd45d070e0f4cd501fa58c"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
