schema_version = 2
component = "tar"
repo = "https://git.savannah.gnu.org/git/tar.git"
branch = "v1.35"
imported_commit = "e545d446dfe6564265cdf4186641ee76f4acc7fa"
imported_at_utc = "2026-08-02T18:24:40.664920570+00:00"
sync_method = "copy"
destination_path = "src/userland/tar"
upstream_tree = "ebf72a162689af8ff91729edb1c72c13f06ff0bb"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "694aab748f9c374398cae6ea8d6dce705c6c8f9e932750a8edefb2e2d3866729"
intentional_omission_policy = "upstream/policies/gitlinks.toml#tar"
gitlink_policy = "upstream/policies/gitlinks.toml#tar"
patch_manifest = "upstream/patches/tar/manifest.toml"
patch_manifest_sha256 = "8d6aca67c771ad57cecf671510c0c6103b4a650e91aab32564e28b766f7c2b69"
