schema_version = 2
component = "udisks2"
repo = "https://github.com/storaged-project/udisks.git"
branch = "udisks-2.11.2"
imported_commit = "caffebe56d8208365cf0d62e0d05d31260d91156"
imported_at_utc = "2026-09-18T05:03:33.832863114+00:00"
sync_method = "copy"
destination_path = "src/system/services/udisks2"
upstream_tree = "4ae3e946bad4aef767fa797af5bdacce7b758e05"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "76a3ca69b6dff9775f4cd618bbf563d34147c42b336448a968703309855edc81"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
