schema_version = 2
component = "upower"
repo = "https://gitlab.freedesktop.org/upower/upower.git"
branch = "v1.91.4"
imported_commit = "af22b0bb6a97fff89b0e11101de9fc4937832864"
imported_at_utc = "2026-09-18T05:03:30.466513003+00:00"
sync_method = "copy"
destination_path = "src/system/services/upower"
upstream_tree = "43694b1da6e3a835ca33cc89c4f55e7932aebf6a"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "0563646867a351cc249e26cc8959ef23647d1933ec071d2010f110b1f3a0896d"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
