schema_version = 2
component = "util-linux"
repo = "https://github.com/util-linux/util-linux.git"
branch = "master"
imported_commit = "fd82c4043fab942b889f478800118c66edfbc39f"
imported_at_utc = "2026-07-31T22:42:36Z"
sync_method = "copy"
destination_path = "src/userland/util-linux"
upstream_tree = "d22c22956a98f6946c75f2cade6f466ccc0bc6dc"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "34bc10548190e5bfbab68b82932d4f47f995db7ec5fca1efa12fec78d0668d3a"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
