schema_version = 2
component = "vulkan-tools"
repo = "https://github.com/KhronosGroup/Vulkan-Tools.git"
branch = "main"
imported_commit = "286299bb6b732e4b22771cfb9d7d421542d40501"
imported_at_utc = "2026-08-15T16:20:56.914616377+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/vulkan-tools"
upstream_tree = "841a1e83e18f23713b1d0cd9cafc16199e78b802"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "1d976f9bcc19769626144ec954487cf7b0189ef67c7fd1b2fc8ae349d2a3510a"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
