schema_version = 2
component = "wayland"
repo = "https://gitlab.freedesktop.org/wayland/wayland.git"
branch = "1.26.0"
imported_commit = "87cc8a8728a923fc57938faa81ba0e74f34ecdc7"
imported_at_utc = "2026-08-13T21:25:05.083811245+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/wayland"
upstream_tree = "a2fad3737670213aea19322e7166da34555ac653"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "2e7f577a2fa85cecd17bf68876a5f670b29d43040f11363bc6a91a19434c8460"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
