schema_version = 2
component = "wayland-protocols"
repo = "https://gitlab.freedesktop.org/wayland/wayland-protocols.git"
branch = "1.46"
imported_commit = "6141e1154303dadd5c3e480bc4a16e26f1dcb2af"
imported_at_utc = "2026-09-12T23:04:24.868984682+00:00"
sync_method = "copy"
destination_path = "src/graphics/wayland-protocols"
upstream_tree = "701208f540030d4c552e50823eba703196e0f5ca"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "08af7d399f05449deef26df1ec60d38fc9bab751af1c546b8d2be4fca8df23a6"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
