schema_version = 2
component = "wireplumber"
repo = "https://gitlab.freedesktop.org/pipewire/wireplumber.git"
branch = "0.5.17"
imported_commit = "11e501181fb87dc8e72e55156d672109fbad2434"
imported_at_utc = "2026-09-18T05:03:25.750806662+00:00"
sync_method = "copy"
destination_path = "src/system/multimedia/wireplumber"
upstream_tree = "2f28c5a36a8498c25457e7f7312fed4d6f02a56e"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "afe7990650b7e59340d3c9765b7e6e960ca7da2203622d2c0a5b4789f0d51cee"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
