schema_version = 2
component = "wireless-regdb"
repo = "https://git.kernel.org/pub/scm/linux/kernel/git/wens/wireless-regdb.git"
branch = "master-2026-09-03"
imported_commit = "389b9b702cf9018e9a9078ccc4fa8eaae2e054e3"
imported_at_utc = "2026-09-29T01:23:20.836400390+00:00"
sync_method = "copy"
destination_path = "src/system/data/wireless-regdb"
upstream_tree = "4c0478dd168e2fbdbee6a8ee735253cccee583a4"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "0fef5164436d26c56449cb9d455770f2e67b61c859a3817843558284d42319b9"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
