schema_version = 2
component = "wireless-regdb"
repo = "https://git.kernel.org/pub/scm/linux/kernel/git/wens/wireless-regdb.git"
branch = "master-2026-05-30"
imported_commit = "b488e68eb1ca0a0dcdf742c7f4195c7678eafdc5"
imported_at_utc = "2026-08-15T01:15:41.119594190+00:00"
sync_method = "copy"
destination_path = "src/system/data/wireless-regdb"
upstream_tree = "40e2222a02439ae8547b0d3e21c50603ce89ed94"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "f4e6d4e41daef3ffc128ef41b81d446a68570c231d1f7f0f15b4f2d473a9fbe4"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
