schema_version = 2
component = "xcb-cursor"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxcb-cursor.git"
branch = "xcb-util-cursor-0.1.6"
imported_commit = "7b0fa99aa13084a9bf7be4180066f6a74b0adef1"
imported_at_utc = "2026-09-15T01:15:02.294236439+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xcb-cursor"
upstream_tree = "b3c906fb59d9b0f7b0eb184f97ac6389f1eea157"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "41161ffcd3a593fddedcdab952b0baeebc2f0082bb240119c3335de54eb0c0da"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
