schema_version = 2
component = "xcb-keysyms"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxcb-keysyms.git"
branch = "xcb-util-keysyms-0.4.1"
imported_commit = "85e093f14b0ade2956e0a5d1c37cfde06d8b1ba6"
imported_at_utc = "2026-09-15T01:15:09.860463579+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xcb-keysyms"
upstream_tree = "6ab57cbfcf79cc166bc49f297fba47f8296c7304"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "803c4f95c4aa623e4a5a53e230b32178db4bc9fcee611e3e12f51de3881944fc"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
