schema_version = 2
component = "xcb-renderutil"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxcb-render-util.git"
branch = "xcb-util-renderutil-0.3.10"
imported_commit = "5293d8b6165f23b9f7a8bcc903da0e4d7a75984c"
imported_at_utc = "2026-09-15T01:16:10.038758794+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xcb-renderutil"
upstream_tree = "375e119cf066f19626222db269b0837a2b249367"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "332fd4757764f71d425eba34309813cee441c5edd8cbd1f5253bc92c063c346f"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
