schema_version = 2
component = "xcb-util"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxcb-util.git"
branch = "master"
imported_commit = "523cbc8af809d9525703f2fa3680d8c880fe4e9c"
imported_at_utc = "2026-09-15T01:24:00.306252456+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xcb-util"
upstream_tree = "0e5b1a785ac4697715d65f1c85526cb5df48b134"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "407a603eaa246f8e37428991ea508562d11fd6c4ffb07d0bf4e59407be5725ad"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
