schema_version = 2
component = "xcb-image"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxcb-image.git"
branch = "xcb-util-image-0.4.1"
imported_commit = "525ce59fe2329d4b23fc0c52ed9dd92daac8ac2a"
imported_at_utc = "2026-09-15T01:16:13.564392815+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xcb-image"
upstream_tree = "bc911be9d187f0c1e529bf653d3099ed79629147"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "bdb8b4704e8ef61abf1afbd42804f6ae9eec7335e8a2d8b9012780bd4274221a"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
