schema_version = 2
component = "xcb-util-wm"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxcb-wm.git"
branch = "xcb-util-wm-0.4.2"
imported_commit = "0c6681e465c9cc7b1fbb60778ba1eaa61ab01a14"
imported_at_utc = "2026-09-15T01:15:05.915686433+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xcb-util-wm"
upstream_tree = "33e6fc3ba82f72170e3929dc278a25ffeb4055a4"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d93b2654a330cc707e39406f24d80fb3149cfad1dcaf24de04b56917f116993e"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
