schema_version = 2
component = "xcb-proto"
repo = "https://gitlab.freedesktop.org/xorg/proto/xcbproto.git"
branch = "xcb-proto-1.17.0"
imported_commit = "77d7fc04da729ddc5ed4aacf30253726fac24dca"
imported_at_utc = "2026-08-15T18:19:07.507460750+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xcb-proto"
upstream_tree = "26da96b71bc2753427bc54ca05f1706715d84b0c"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "33b1e66c8427cac139fbf388ceb38008440b898634adbde2a72c53937b3837d8"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
