schema_version = 2
component = "xcursorgen"
repo = "https://gitlab.freedesktop.org/xorg/app/xcursorgen.git"
branch = "xcursorgen-1.0.9"
imported_commit = "3d0909b630ca82401489411c9b496de14f664c55"
imported_at_utc = "2026-09-25T01:01:13.635227278+00:00"
sync_method = "copy"
destination_path = "src/build-tools/xcursorgen"
upstream_tree = "410ec6defa5512991ddfd7430274716cf9ce9d73"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "5ba5cc2b9804732e030bcb0b4d15b4ffcb28b10c41e5ab91e5e7018bbc5ca432"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
