schema_version = 2
component = "xdg-desktop-portal-gvdb"
repo = "https://gitlab.gnome.org/GNOME/gvdb.git"
branch = "main"
imported_commit = "c6f2359cc1d00f16e0a0e2527fa0bc1882b8b5ab"
imported_at_utc = "2026-08-29T01:17:48.471319119+00:00"
sync_method = "copy"
destination_path = "src/system/packages/xdg-desktop-portal-gvdb"
upstream_tree = "923939f1c00cb103e4497e38f7c6ec0af9c0e40b"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "7e0c511c6b93baf47dd725194a6479899cddf34a97dbcc14d9fcf93ffea6f601"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
