schema_version = 2
component = "xdg-desktop-portal-kde"
repo = "https://invent.kde.org/plasma/xdg-desktop-portal-kde.git"
branch = "v6.6.5"
imported_commit = "e83c8c953700168b01b5884120a71879babeba81"
imported_at_utc = "2026-09-18T00:48:28.065858370+00:00"
sync_method = "copy"
destination_path = "src/desktop/kde/xdg-desktop-portal-kde"
upstream_tree = "c0790bcffc441d480e280f24b5c66c958762bc17"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "6027399bef3a7f7dcfb0ad6c4b71f0981c319a8c7906dfa005302dd6bf22b831"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
