schema_version = 2
component = "xdg-desktop-portal-libglnx"
repo = "https://gitlab.gnome.org/GNOME/libglnx.git"
branch = "master"
imported_commit = "ff64d52116ae74f0d25e24f089db28921ea171ff"
imported_at_utc = "2026-08-29T01:17:54.228686271+00:00"
sync_method = "copy"
destination_path = "src/system/packages/xdg-desktop-portal-libglnx"
upstream_tree = "dddfab414e0ed1d30034e7ba341d119e96a31225"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "c4295aff9f3b91a606899f6044790fcaa5626303eab131ab8a69cf09ea5330c5"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
