schema_version = 2
component = "xdg-desktop-portal"
repo = "https://github.com/flatpak/xdg-desktop-portal.git"
branch = "1.22.1"
imported_commit = "1d20fadc304f6601452b5db65ed91197dba77041"
imported_at_utc = "2026-08-29T00:21:10.022181489+00:00"
sync_method = "copy"
destination_path = "src/system/packages/xdg-desktop-portal"
upstream_tree = "2d4a119aff88e268a558510774915bbac87b0a19"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "99b5003ead18f4eb01e8e57a144a3198950044dd5e4aa4f91cecfad8ba00ed49"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
