schema_version = 2
component = "xdg-desktop-portal-cosmic"
repo = "https://github.com/pop-os/xdg-desktop-portal-cosmic.git"
branch = "master"
imported_commit = "f211aa37d45e443c9060b08c725d6fa73431565f"
imported_at_utc = "2026-08-15T23:34:27.648284112+00:00"
sync_method = "copy"
destination_path = "src/desktop/cosmic/xdg-desktop-portal-cosmic"
upstream_tree = "22edeb176b435404cd3b842088703e92965034a0"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "1765a0924c4e18379816b6001fa87256cd97aa5f1c75c2e89120c9ab630964e4"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
