schema_version = 2
component = "xdg-dbus-proxy"
repo = "https://github.com/flatpak/xdg-dbus-proxy.git"
branch = "0.1.7"
imported_commit = "6a170fa77e3cbecb48f9dd2478fe5c0a119eb467"
imported_at_utc = "2026-08-29T21:28:51.762819764+00:00"
sync_method = "copy"
destination_path = "src/system/packages/xdg-dbus-proxy"
upstream_tree = "7b7aa4dc17e6942c0c2d512836c7ef7d3f5af679"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "c17f2811e6f7f3de5a06a8c956e70c9263d9b2e9228b3296c4c00d6a93bcfa16"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
