schema_version = 2
component = "xkbcomp"
repo = "https://gitlab.freedesktop.org/xorg/app/xkbcomp.git"
branch = "master"
imported_commit = "4e36eaa6b6530c195a0c59f0bbab86aa8512c26e"
imported_at_utc = "2026-08-29T04:53:52.268473594+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xkbcomp"
upstream_tree = "a75a594f75b40a4c7712514a42d85d6dc9860326"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "a8d947ac67e02cbd08df031c66e0b3719c34360b87d5a7abb8abb9a27eb75716"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
