schema_version = 2
component = "xkeyboard-config"
repo = "https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config.git"
branch = "xkeyboard-config-2.46"
imported_commit = "4225e14a2d0fca5a4f9cb8517cf12d96ea290d84"
imported_at_utc = "2026-08-13T18:05:12.860943277+00:00"
sync_method = "copy"
destination_path = "src/system/data/xkeyboard-config"
upstream_tree = "2754f7ba9bd16304608a2fb560f27b5d7f9699a1"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "11923b6873ccc498a67c33501ac2e78f877e91156ba3b1c00d5727f4eaee94c9"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
