schema_version = 2
component = "xorgproto"
repo = "https://gitlab.freedesktop.org/xorg/proto/xorgproto.git"
branch = "xorgproto-2024.1"
imported_commit = "67469711055522b8adb2d795b01e7ba98cb8816c"
imported_at_utc = "2026-08-15T18:18:43.687100206+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xorgproto"
upstream_tree = "94fc4b27f300ec766f7f14b7ee2f2d5bc54d44f1"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "31bf57a089714d72fa297a14c80c955cc1119d24c86ab1ed69d5bb4fff4f0471"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
