schema_version = 2
component = "xorg-util-macros"
repo = "https://gitlab.freedesktop.org/xorg/util/macros.git"
branch = "util-macros-1.20.2"
imported_commit = "a9d71e3fd8e6758b70be31c586921bbbcd2a8449"
imported_at_utc = "2026-08-15T18:26:34.465915424+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xorg-util-macros"
upstream_tree = "efb6845f57b29925ded382ea0ed194341f01ade9"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "603b2ce34c069319c646eabbf8ad42e87ee5c974e1377a00b8834f26f81eb10f"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
