schema_version = 2
component = "xtrans"
repo = "https://gitlab.freedesktop.org/xorg/lib/libxtrans.git"
branch = "xtrans-1.5.2"
imported_commit = "0dc46e7ed5bdd876467f9dbb314ba6b8094e541b"
imported_at_utc = "2026-08-15T18:18:48.378012048+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xtrans"
upstream_tree = "6b248c3bebbc3c489acb17e17ea30091e4f3f276"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d2516cf8cc7646d7329cc9af306f1317be95f57bb7941b12c66d649ff8c63d02"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
