schema_version = 2
component = "xwayland"
repo = "https://gitlab.freedesktop.org/xorg/xserver.git"
branch = "xwayland-24.1.13"
imported_commit = "c5a47fda896aeefbf1d06a73e392a294344f9e1a"
imported_at_utc = "2026-08-29T00:21:04.426620618+00:00"
sync_method = "copy"
destination_path = "src/system/graphics/xwayland"
upstream_tree = "500ea7db0672386c782b17fa6332681ec0141a6b"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "d19ee3b636d09402f65633be9f208510d45eddeae7f13cc2ac923d095d20adf3"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
