schema_version = 2
component = "xz"
repo = "https://github.com/tukaani-project/xz.git"
branch = "v5.8.4"
imported_commit = "d3e650e63c110e830fd5391e7f8b45df0b91d3da"
imported_at_utc = "2026-09-29T01:23:22.474526295+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/xz"
upstream_tree = "c61bcc5e09ba6a6a980c4227ea5cbe995508c5b8"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "b48021e7a782faf17bdfbef30b4ce83776a08f6028f0ef2247d2a48ab48e11a0"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
