schema_version = 2
component = "yaml-cpp"
repo = "https://github.com/jbeder/yaml-cpp.git"
branch = "0.8.0"
imported_commit = "f7320141120f720aecc4c32be25586e7da9eb978"
imported_at_utc = "2026-09-11T20:38:06.322291446+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/yaml-cpp"
upstream_tree = "1c4757f20f8dd4f5a9d86969bf17bf8cf3a41e99"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "38ce7f58908adb746cabe7cea1f2efc5de756dbbcb8a9930e4e40e28c58a6734"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "upstream/patches/yaml-cpp/manifest.toml"
patch_manifest_sha256 = "945a97529b2fd9ea29a275d7cca6620b5cc18a9e6bcdfe48642473b6021ae60e"
lfs_policy = "none"
lfs_policy_sha256 = "none"
