schema_version = 2
component = "zxing-cpp"
repo = "https://github.com/zxing-cpp/zxing-cpp.git"
branch = "v3.1.1"
imported_commit = "287c85df6f961c8efbfb5ffd736cd9457b8b890e"
imported_at_utc = "2026-09-18T04:41:28.297987239+00:00"
sync_method = "copy"
destination_path = "src/system/libraries/zxing-cpp"
upstream_tree = "70859722c52c0dcaae0053b7a919249900910731"
imported_tree_digest_algorithm = "sha256-git-ls-tree-no-gitlinks-v1"
imported_tree_digest = "495d25df5c0760d6fb924b6848bdfef69e10aec41bd5b560ccbbb4dcc3546915"
source_selection_policy = "none"
source_selection_policy_sha256 = "none"
intentional_omission_policy = "none"
gitlink_policy = "none"
patch_manifest = "none"
patch_manifest_sha256 = "none"
lfs_policy = "none"
lfs_policy_sha256 = "none"
