---
efiSystemPartition: /boot/efi
defaultFileSystemType: btrfs
defaultPartitionTableType: gpt
initialPartitioningChoice: erase
requiredStorage: 15GiB
neverCreateSwap: true
drawNestedPartitions: false
alwaysShowPartitionLabels: true
