use anyhow::{bail, Result};
use serde::Serialize;
use std::collections::{BTreeMap, BTreeSet};

#[cfg(test)]
mod wifi_grub_tests {
    use super::*;
    #[test]
    fn wifi_and_bootloader_runtime_dependencies_are_complete() {
        let specs = package_specs();
        let network = specs.iter().find(|p| p.name == "network-manager").unwrap();
        assert!(network.depends.contains(&"wpasupplicant"));
        let supplicant = specs.iter().find(|p| p.name == "wpasupplicant").unwrap();
        for dependency in ["libnl-3-200", "libnl-genl-3-200", "libssl3t64", "libdbus-1-3"] {
            assert!(supplicant.depends.contains(&dependency));
        }
        assert!(specs.iter().find(|p| p.name == "mattos-installer").unwrap().depends.contains(&"grub-efi-amd64"));
    }
}

pub(crate) const PACKAGE_NAMES: &[&str] = &[
    "mattos-filesystem",
    "mattos-compat",
    "libc6",
    "libgcc-s1",
    "libstdc++6",
    "linux-libc-dev",
    "linux-modules-7.2.0-rc5-mattos",
    "libc6-dev",
    "mattos-libgcc-dev",
    "mattos-libstdc++-dev",
    "binutils",
    "mattos-gcc-common",
    "cpp",
    "gcc",
    "g++",
    "make",
    "libc-bin",
    "locales",
    "iso-codes",
    "tzdata",
    "linux-firmware",
    "wireless-regdb",
    "mattos-base-files",
    "ca-certificates",
    "mattos-brush",
    "coreutils",
    "curl",
    "libmd0",
    "libbsd0",
    "libzstd1",
    "mattos-libcrypto3",
    "libssl3t64",
    "libelf1t64",
    "libpcre2-8-0",
    "libselinux1",
    "libcrypt1",
    "libblkid1",
    "libmount1",
    "libsmartcols1",
    "libuuid1",
    "libfdisk1",
    "mount",
    "util-linux",
    "dpkg",
    "libgpg-error0",
    "libgcrypt20",
    "libassuan9",
    "libksba8",
    "libnpth0",
    "gpgv",
    "gnupg",
    "libapt-pkg7.0",
    "apt",
    "mattos-libtinfow6",
    "libncursesw6",
    "libreadline8",
    "libndp0",
    "ncurses-base",
    "ncurses-bin",
    "libkmod2",
    "kmod",
    "mattos-libproc2",
    "procps",
    "libsystemd0",
    "libudev1",
    "udev",
    "libexpat1",
    "libcap2",
    "libattr1",
    "libacl1",
    "zlib1g",
    "libbz2-1.0",
    "gzip",
    "bzip2",
    "liblz4-1",
    "liblzma5",
    "xz-utils",
    "libxxhash0",
    "tar",
    "zstd",
    "patch",
    "libmagic1",
    "file",
    "less",
    "git",
    "openssh-client",
    "openssh-server",
    "libffi8",
    "libffi-dev",
    "libwayland-client0",
    "libwayland-server0",
    "libwayland-egl1",
    "libxkbcommon0",
    "xkb-data",
    "libseat1",
    "libdisplay-info3",
    "libevdev2",
    "libinput10",
    "libpixman-1-0",
    "libdrm2",
    "libdrm-amdgpu1",
    "libdrm-nouveau2",
    "libxau6",
    "libxdmcp6",
    "libxcb1",
    "libx11-6",
    "libxext6",
    "libglvnd0",
    "libglx0",
    "libgl1",
    "libopengl0",
    "libgbm1",
    "libegl1",
    "libgles1",
    "libgles2",
    "libegl-mesa0",
    "libgl1-mesa-dri",
    "libvulkan1",
    "libvulkan-dev",
    "mesa-vulkan-drivers",
    "vulkan-tools",
    "linux-modules-nvidia-595-open-7.2.0-rc5-mattos",
    "nvidia-firmware-595",
    "libnvidia-gl-595",
    "libnvidia-compute-595",
    "libnvidia-encode-595",
    "libnvidia-decode-595",
    "nvidia-utils-595",
    "nvidia-driver-595-open",
    "cosmic-comp",
    "cosmic-edit",
    "cosmic-initial-setup",
    "cosmic-desktop",
    "flatpak",
    "xwayland",
    "xdg-desktop-portal",
    "libduktape207",
    "polkit",
    "network-manager",
    "libnl-3-200",
    "libnl-genl-3-200",
    "wpasupplicant",
    "grub-efi-amd64",
    "mattos-cozy",
    "libpython3.14",
    "python3",
    "python3-venv",
    "python3-dev",
    "libllvm22",
    "llvm",
    "llvm-dev",
    "clang",
    "lld",
    "rustc",
    "cargo",
    "libdbus-1-3",
    "libdav1d7",
    "libglib2.0-0t64",
    "pipewire",
    "dbus-broker",
    "libpam0g",
    "mattos-libpam-misc0",
    "libpam-modules",
    "libpam-runtime",
    "passwd",
    "mattos-sudo-rs",
    "login",
    "iproute2",
    "iputils-ping",
    "btrfs-progs",
    "dosfstools",
    "e2fsprogs",
    "mattos-installer",
];

#[derive(Clone, Debug, Serialize)]
pub(crate) struct PackageSpec {
    pub(super) name: &'static str,
    pub(super) description: &'static str,
    pub(super) source_component: &'static str,
    pub(super) depends: &'static [&'static str],
    pub(super) provides: &'static [&'static str],
    pub(super) conflicts: &'static [&'static str],
    pub(super) replaces: &'static [&'static str],
    pub(super) essential: bool,
    pub(super) priority: &'static str,
}

pub(crate) fn package_specs() -> Vec<PackageSpec> {
    vec![
        PackageSpec {
            name: "mattos-filesystem",
            description: "MattOS base filesystem hierarchy",
            source_component: "MattOS",
            depends: &[],
            provides: &["mattos-filesystem-hierarchy"],
            conflicts: &[],
            replaces: &[],
            essential: true,
            priority: "required",
        },
        PackageSpec {
            name: "libc6",
            description: "GNU C Library runtime built for MattOS",
            source_component: "glibc",
            depends: &["mattos-filesystem"],
            provides: &["libc6", "mattos-runtime-abi"],
            conflicts: &[],
            replaces: &[],
            essential: true,
            priority: "required",
        },
        PackageSpec {
            name: "mattos-compat",
            description: "Isolated Debian, Fedora, and Pop!_OS application compatibility manager",
            source_component: "mattos-compat",
            depends: &[
                "mattos-filesystem",
                "libsystemd0",
                "libcap2",
                "libmount1",
                "libblkid1",
                "libselinux1",
                "liblzma5",
                "libzstd1",
            ],
            provides: &["mattos-compat"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libgcc-s1",
            description: "GCC shared unwinding runtime built for MattOS",
            source_component: "gcc",
            depends: &["mattos-filesystem", "libc6"],
            provides: &["libgcc-s1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "libstdc++6",
            description: "GNU C++ runtime library built for MattOS",
            source_component: "gcc",
            depends: &["mattos-filesystem", "libc6", "libgcc-s1"],
            provides: &["libstdc++6"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "linux-libc-dev",
            description: "Linux userspace API headers for MattOS native development",
            source_component: "linux",
            depends: &["mattos-filesystem"],
            provides: &["linux-libc-dev"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "linux-modules-7.2.0-rc5-mattos",
            description: "MattOS generic x86_64 kernel modules and depmod metadata",
            source_component: "kernel-modules",
            depends: &["kmod"],
            provides: &["linux-modules-amd64", "linux-modules-generic"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libc6-dev",
            description: "GNU C Library headers and link-time files for MattOS",
            source_component: "glibc",
            depends: &["libc6", "linux-libc-dev"],
            provides: &["libc6-dev"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "mattos-libgcc-dev",
            description: "GCC support headers and static link libraries for MattOS",
            source_component: "gcc",
            depends: &["libc6-dev", "libgcc-s1"],
            provides: &["libgcc-dev"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "mattos-libstdc++-dev",
            description: "GNU C++ standard library headers and link-time files for MattOS",
            source_component: "gcc",
            depends: &["libc6-dev", "mattos-libgcc-dev", "libstdc++6"],
            provides: &["libstdc++-dev"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "binutils",
            description: "GNU binary utilities built natively for MattOS",
            source_component: "binutils",
            depends: &["libc6"],
            provides: &["binutils"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "mattos-gcc-common",
            description: "Shared compiler support and internal GCC helpers for MattOS",
            source_component: "gcc",
            depends: &["binutils", "mattos-libgcc-dev", "libstdc++6", "zlib1g"],
            provides: &["gcc-common"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "cpp",
            description: "GNU C preprocessor built natively for MattOS",
            source_component: "gcc",
            depends: &["mattos-gcc-common"],
            provides: &["cpp"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "gcc",
            description: "GNU C compiler built natively for MattOS",
            source_component: "gcc",
            depends: &["cpp", "mattos-gcc-common", "libc6-dev"],
            provides: &["c-compiler", "gcc"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "g++",
            description: "GNU C++ compiler built natively for MattOS",
            source_component: "gcc",
            depends: &["gcc", "mattos-libstdc++-dev"],
            provides: &["c++-compiler", "g++"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "make",
            description: "GNU Make built natively for MattOS",
            source_component: "make",
            depends: &["libc6"],
            provides: &["make"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libc-bin",
            description: "GNU C Library runtime utilities built for MattOS",
            source_component: "glibc",
            depends: &["mattos-filesystem", "libc6"],
            provides: &["libc-bin"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "locales",
            description: "glibc locale source data and localedef utility for offline MattOS locale generation",
            source_component: "glibc",
            depends: &["libc6", "libc-bin"],
            provides: &["locales"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "iso-codes",
            description: "Pinned ISO language and territory metadata for offline COSMIC locale selection",
            source_component: "iso-codes",
            depends: &["libc6"],
            provides: &["iso-codes"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "tzdata",
            description: "IANA timezone database built from pinned tzdata source",
            source_component: "tzdata",
            depends: &["libc6"],
            provides: &["tzdata"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "linux-firmware",
            description: "Broad upstream Linux firmware collection for supported modern hardware",
            source_component: "linux-firmware",
            depends: &["mattos-filesystem"],
            provides: &["linux-firmware", "firmware-linux"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "wireless-regdb",
            description: "Signed wireless regulatory database built from pinned upstream data",
            source_component: "wireless-regdb",
            depends: &["mattos-filesystem"],
            provides: &["wireless-regdb"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "mattos-base-files",
            description: "MattOS identity and baseline configuration",
            source_component: "MattOS",
            depends: &["mattos-filesystem"],
            provides: &["mattos-release"],
            conflicts: &["base-files"],
            replaces: &["base-files"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "ca-certificates",
            description: "Pinned Mozilla certificate authority bundle for MattOS",
            source_component: "ca-certificates",
            depends: &["mattos-filesystem"],
            provides: &["ca-certificates"],
            conflicts: &["ca-certificates"],
            replaces: &["ca-certificates"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "mattos-brush",
            description: "Brush shell with sh and bash entry points built for MattOS",
            source_component: "brush",
            depends: &["mattos-filesystem", "libgcc-s1"],
            provides: &["mattos-shell", "sh", "bash"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "coreutils",
            description: "uutils core utilities built for MattOS",
            source_component: "coreutils",
            depends: &["mattos-filesystem", "libgcc-s1"],
            provides: &["coreutils"],
            conflicts: &["coreutils"],
            replaces: &["coreutils"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "curl",
            description: "curl command-line transfer client built for MattOS",
            source_component: "curl",
            depends: &[
                "mattos-filesystem",
                "ca-certificates",
                "zlib1g",
                "libzstd1",
                "mattos-libcrypto3",
                "libssl3t64",
            ],
            provides: &["curl"],
            conflicts: &["curl"],
            replaces: &["curl"],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libmd0",
            description: "libmd message-digest runtime library built for MattOS",
            source_component: "libmd",
            depends: &[],
            provides: &["libmd0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libbsd0",
            description: "libbsd portability runtime library built for MattOS",
            source_component: "libbsd",
            depends: &["libmd0"],
            provides: &["libbsd0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libzstd1",
            description: "Zstandard compression runtime library built for MattOS",
            source_component: "zstd",
            depends: &[],
            provides: &["libzstd1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "mattos-libcrypto3",
            description: "OpenSSL cryptography runtime library built for MattOS",
            source_component: "openssl",
            depends: &["zlib1g", "libzstd1"],
            provides: &["libcrypto3"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libssl3t64",
            description: "OpenSSL TLS runtime library built for MattOS",
            source_component: "openssl",
            depends: &["mattos-libcrypto3", "zlib1g", "libzstd1"],
            provides: &["libssl3t64"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libelf1t64",
            description: "elfutils libelf runtime library built for MattOS",
            source_component: "elfutils",
            depends: &["zlib1g", "libzstd1"],
            provides: &["libelf1t64"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libpcre2-8-0",
            description: "PCRE2 8-bit regular expression runtime library built for MattOS",
            source_component: "pcre2",
            depends: &[],
            provides: &["libpcre2-8-0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libselinux1",
            description: "SELinux userspace runtime library built for MattOS",
            source_component: "selinux",
            depends: &["libpcre2-8-0"],
            provides: &["libselinux1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libcrypt1",
            description: "libxcrypt password hashing runtime library built for MattOS",
            source_component: "libxcrypt",
            depends: &[],
            provides: &["libcrypt1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "libblkid1",
            description: "util-linux block device identification runtime library built for MattOS",
            source_component: "util-linux",
            depends: &[],
            provides: &["libblkid1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libmount1",
            description: "util-linux mount runtime library built for MattOS",
            source_component: "util-linux",
            depends: &["libblkid1"],
            provides: &["libmount1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libsmartcols1",
            description: "util-linux structured table runtime library built for MattOS",
            source_component: "util-linux",
            depends: &[],
            provides: &["libsmartcols1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "mount",
            description: "util-linux mount and unmount tools built for MattOS",
            source_component: "util-linux",
            depends: &["libblkid1", "libmount1", "libsmartcols1", "libselinux1"],
            provides: &["mount"],
            conflicts: &["mount"],
            replaces: &["mount"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "dpkg",
            description: "dpkg binary package management runtime built for MattOS",
            source_component: "dpkg",
            depends: &[
                "mattos-filesystem",
                "tar",
                "zlib1g",
                "libbz2-1.0",
                "liblzma5",
                "libzstd1",
                "libmd0",
                "libpcre2-8-0",
                "libselinux1",
            ],
            provides: &["dpkg"],
            conflicts: &["dpkg"],
            replaces: &["dpkg"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "libgpg-error0",
            description: "GnuPG error and runtime support library built for MattOS",
            source_component: "libgpg-error",
            depends: &[],
            provides: &["libgpg-error0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libgcrypt20",
            description: "GnuPG cryptographic runtime library built for MattOS",
            source_component: "libgcrypt",
            depends: &["libgpg-error0"],
            provides: &["libgcrypt20"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libassuan9",
            description: "GnuPG IPC runtime library built for MattOS",
            source_component: "libassuan",
            depends: &["libgpg-error0"],
            provides: &["libassuan9"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libksba8",
            description: "GnuPG X.509 and CMS runtime library built for MattOS",
            source_component: "libksba",
            depends: &["libgpg-error0"],
            provides: &["libksba8"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libnpth0",
            description: "GnuPG non-preemptive threading runtime library built for MattOS",
            source_component: "npth",
            depends: &[],
            provides: &["libnpth0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "gpgv",
            description: "Source-built OpenPGP signature verifier used by APT",
            source_component: "gnupg",
            depends: &[
                "libc6",
                "zlib1g",
                "libgpg-error0",
                "libgcrypt20",
                "libassuan9",
                "libksba8",
                "libnpth0",
            ],
            provides: &["gpgv"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "gnupg",
            description: "Source-built OpenPGP engine required for verified Flatpak remotes",
            source_component: "gnupg",
            depends: &[
                "libc6",
                "zlib1g",
                "libgpg-error0",
                "libgcrypt20",
                "libassuan9",
                "libksba8",
                "libnpth0",
            ],
            provides: &["gnupg", "gpg"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libapt-pkg7.0",
            description: "APT public runtime library built for MattOS",
            source_component: "apt",
            depends: &[
                "libgcc-s1",
                "libstdc++6",
                "libudev1",
                "libsystemd0",
                "zlib1g",
                "libbz2-1.0",
                "liblz4-1",
                "liblzma5",
                "libxxhash0",
                "libzstd1",
                "mattos-libcrypto3",
                "libssl3t64",
                "gpgv",
            ],
            provides: &["libapt-pkg7.0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "apt",
            description: "APT command-line package manager and local repository methods for MattOS",
            source_component: "apt",
            depends: &[
                "libgcc-s1",
                "libstdc++6",
                "ca-certificates",
                "dpkg",
                "libapt-pkg7.0",
                "libudev1",
                "libsystemd0",
                "zlib1g",
                "libbz2-1.0",
                "liblz4-1",
                "liblzma5",
                "libxxhash0",
                "libzstd1",
                "mattos-libcrypto3",
                "libssl3t64",
                "gpgv",
            ],
            provides: &["apt"],
            conflicts: &["apt"],
            replaces: &["apt"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "mattos-libtinfow6",
            description: "ncurses wide-character terminfo runtime library built for MattOS",
            source_component: "ncurses",
            depends: &[],
            provides: &[],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libncursesw6",
            description: "ncurses wide-character runtime library built for MattOS",
            source_component: "ncurses",
            depends: &["mattos-libtinfow6"],
            provides: &["libncursesw6"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "ncurses-base",
            description: "MattOS essential terminal capability database",
            source_component: "ncurses",
            depends: &["mattos-filesystem"],
            provides: &["terminfo"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "ncurses-bin",
            description: "ncurses terminal utilities built for MattOS",
            source_component: "ncurses",
            depends: &["mattos-libtinfow6", "ncurses-base"],
            provides: &["ncurses-bin"],
            conflicts: &["ncurses-bin"],
            replaces: &["ncurses-bin"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libreadline8",
            description: "GNU Readline runtime library built for MattOS",
            source_component: "readline",
            depends: &["libc6"],
            provides: &["libreadline8"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libndp0",
            description: "IPv6 Neighbor Discovery Protocol runtime library built for MattOS",
            source_component: "libndp",
            depends: &["libc6"],
            provides: &["libndp0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libkmod2",
            description: "kmod runtime library built for MattOS",
            source_component: "kmod",
            depends: &["libzstd1"],
            provides: &["libkmod2"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "kmod",
            description: "Linux kernel module management tools built for MattOS",
            source_component: "kmod",
            depends: &["libkmod2"],
            provides: &["kmod"],
            conflicts: &["kmod"],
            replaces: &["kmod"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "mattos-libproc2",
            description: "procps process information runtime library built for MattOS",
            source_component: "procps-ng",
            depends: &[],
            provides: &[],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "procps",
            description: "procps process inspection utilities built for MattOS",
            source_component: "procps-ng",
            depends: &["mattos-libproc2", "libncursesw6", "mattos-libtinfow6"],
            provides: &["procps"],
            conflicts: &["procps"],
            replaces: &["procps"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libsystemd0",
            description: "systemd public runtime library built for MattOS",
            source_component: "systemd",
            depends: &[],
            provides: &["libsystemd0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libudev1",
            description: "systemd device enumeration runtime library built for MattOS",
            source_component: "systemd",
            depends: &[],
            provides: &["libudev1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "udev",
            description: "udev hardware database sources and prebuilt database for MattOS",
            source_component: "systemd",
            depends: &["libudev1", "libblkid1"],
            provides: &["udev"],
            conflicts: &["udev"],
            replaces: &["udev"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libexpat1",
            description: "Expat XML parser runtime library built for MattOS",
            source_component: "expat",
            depends: &[],
            provides: &["libexpat1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libcap2",
            description: "Linux capabilities runtime library built for MattOS",
            source_component: "libcap",
            depends: &[],
            provides: &["libcap2"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libattr1",
            description: "Extended attribute runtime library built for MattOS",
            source_component: "attr",
            depends: &[],
            provides: &["libattr1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libacl1",
            description: "POSIX access control list runtime library built for MattOS",
            source_component: "acl",
            depends: &[],
            provides: &["libacl1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "zlib1g",
            description: "zlib compression runtime library built for MattOS",
            source_component: "zlib",
            depends: &[],
            provides: &["zlib1g"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libbz2-1.0",
            description: "bzip2 compression runtime library built for MattOS",
            source_component: "bzip2",
            depends: &[],
            provides: &["libbz2-1.0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "liblz4-1",
            description: "LZ4 compression runtime library built for MattOS",
            source_component: "lz4",
            depends: &[],
            provides: &["liblz4-1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "liblzma5",
            description: "XZ Utils liblzma compression runtime library built for MattOS",
            source_component: "xz",
            depends: &[],
            provides: &["liblzma5"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libxxhash0",
            description: "xxHash runtime library built for MattOS",
            source_component: "xxhash",
            depends: &[],
            provides: &["libxxhash0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "tar",
            description: "GNU tar archive utility built for MattOS",
            source_component: "tar",
            depends: &["libacl1"],
            provides: &["tar"],
            conflicts: &["tar"],
            replaces: &["tar"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "libdbus-1-3",
            description: "Reference D-Bus client library and private-session tools built for MattOS",
            source_component: "dbus",
            depends: &["libexpat1"],
            provides: &["libdbus-1-3"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libdav1d7",
            description: "AV1 decoder runtime used by COSMIC image handling",
            source_component: "dav1d",
            depends: &["libc6"],
            provides: &["libdav1d7"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libglib2.0-0t64",
            description: "GLib, GObject, and GIO runtime for the COSMIC desktop",
            source_component: "glib",
            depends: &["libc6", "libffi8", "libpcre2-8-0", "zlib1g"],
            provides: &["libglib2.0-0", "libglib2.0-0t64"],
            conflicts: &[],
            replaces: &["libglib2.0-0"],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "pipewire",
            description: "PipeWire audio service, PulseAudio compatibility, and SPA runtime",
            source_component: "pipewire",
            depends: &["libc6", "libdbus-1-3", "libsystemd0"],
            provides: &[
                "pipewire",
                "pipewire-pulse",
                "libpipewire-0.3-0",
                "libspa-0.2-modules",
            ],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "dbus-broker",
            description: "D-Bus message broker and MattOS bus policy",
            source_component: "dbus-broker",
            depends: &["libexpat1", "libsystemd0"],
            provides: &["dbus-system-bus"],
            // MattOS keeps the reference daemon only for dbus-run-session and
            // private buses.  The broker owns the system/user systemd units;
            // the two package payloads do not overlap.
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libpam0g",
            description: "Linux PAM core runtime library built for MattOS",
            source_component: "linux-pam",
            depends: &[],
            provides: &["libpam0g"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "mattos-libpam-misc0",
            description: "Linux PAM miscellaneous runtime library built for MattOS",
            source_component: "linux-pam",
            depends: &["libpam0g"],
            provides: &["libpam-misc0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "libpam-modules",
            description: "Linux PAM authentication modules built for MattOS",
            source_component: "linux-pam",
            depends: &["libpam0g", "libcrypt1"],
            provides: &["libpam-modules"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "libpam-runtime",
            description: "MattOS PAM policy and authentication helper runtime",
            source_component: "linux-pam",
            depends: &["libpam0g", "libpam-modules", "libcrypt1"],
            provides: &["libpam-runtime"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "passwd",
            description: "Shadow account administration tools built for MattOS",
            source_component: "shadow",
            depends: &[
                "libpam0g",
                "mattos-libpam-misc0",
                "libpam-runtime",
                "libbsd0",
                "libmd0",
                "libcrypt1",
            ],
            provides: &["passwd"],
            conflicts: &["passwd"],
            replaces: &["passwd"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "mattos-sudo-rs",
            description: "Privilege delegation tools built for MattOS",
            source_component: "sudo-rs",
            depends: &["libgcc-s1", "libpam0g", "libpam-runtime"],
            provides: &["sudo"],
            conflicts: &["sudo"],
            replaces: &["sudo"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "login",
            description: "util-linux login, su, and agetty tools built for MattOS",
            source_component: "util-linux",
            depends: &["libpam0g", "mattos-libpam-misc0", "libpam-runtime"],
            provides: &["login"],
            conflicts: &["login"],
            replaces: &["login"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "iproute2",
            description: "Linux routing and network configuration tools built for MattOS",
            source_component: "iproute2",
            depends: &[
                "libcap2",
                "zlib1g",
                "libzstd1",
                "libelf1t64",
                "libpcre2-8-0",
                "libselinux1",
            ],
            provides: &["iproute2"],
            conflicts: &["iproute2"],
            replaces: &["iproute2"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "iputils-ping",
            description: "Linux ping and tracepath network diagnostics built for MattOS",
            source_component: "iputils",
            depends: &[],
            provides: &["iputils-ping"],
            conflicts: &["iputils-ping"],
            replaces: &["iputils-ping"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "btrfs-progs",
            description: "Btrfs filesystem administration tools built for MattOS",
            source_component: "btrfs-progs",
            depends: &["libc6", "libblkid1", "libuuid1", "zlib1g", "libzstd1"],
            provides: &["btrfs-progs"],
            conflicts: &["btrfs-progs"],
            replaces: &["btrfs-progs"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "dosfstools",
            description: "FAT filesystem administration tools built for MattOS",
            source_component: "dosfstools",
            depends: &["libc6"],
            provides: &["dosfstools"],
            conflicts: &["dosfstools"],
            replaces: &["dosfstools"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "e2fsprogs",
            description: "ext2/ext3/ext4 filesystem utilities built for MattOS",
            source_component: "e2fsprogs",
            depends: &["libc6", "libblkid1", "libuuid1"],
            provides: &["e2fsprogs"],
            conflicts: &["e2fsprogs"],
            replaces: &["e2fsprogs"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "mattos-installer",
            description: "MattOS shared installation backend with CLI and native COSMIC frontends",
            source_component: "installer",
            depends: &[
                "libc6",
                "libgcc-s1",
                "util-linux",
                "libblkid1",
                "libuuid1",
                "zlib1g",
                "libzstd1",
                "passwd",
                "coreutils",
                "xz-utils",
                "btrfs-progs",
                "dosfstools",
                "e2fsprogs",
                "libcrypt1",
                "libwayland-client0",
                "libxkbcommon0",
                "cosmic-comp",
                "linux-modules-7.2.0-rc5-mattos",
                "linux-firmware",
                "wireless-regdb",
                "grub-efi-amd64",
            ],
            provides: &[
                "mattos-installer",
                "mattos-installer-cli",
                "mattos-installer-cosmic",
            ],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libuuid1",
            description: "util-linux UUID runtime library built for MattOS",
            source_component: "util-linux",
            depends: &[],
            provides: &["libuuid1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libfdisk1",
            description: "util-linux partitioning runtime library built for MattOS",
            source_component: "util-linux",
            depends: &["libblkid1", "libuuid1", "libsmartcols1"],
            provides: &["libfdisk1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "util-linux",
            description: "Essential Linux system administration utilities built for MattOS",
            source_component: "util-linux",
            depends: &[
                "libblkid1",
                "libmount1",
                "libsmartcols1",
                "libuuid1",
                "libfdisk1",
                "libselinux1",
                "libncursesw6",
                "mattos-libtinfow6",
            ],
            provides: &["util-linux"],
            conflicts: &["util-linux"],
            replaces: &["util-linux"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "gzip",
            description: "GNU gzip compression tools built for MattOS",
            source_component: "gzip",
            depends: &[],
            provides: &["gzip"],
            conflicts: &["gzip"],
            replaces: &["gzip"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "bzip2",
            description: "bzip2 compression tools built for MattOS",
            source_component: "bzip2",
            depends: &["libbz2-1.0"],
            provides: &["bzip2"],
            conflicts: &["bzip2"],
            replaces: &["bzip2"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "xz-utils",
            description: "XZ compression tools built for MattOS",
            source_component: "xz",
            depends: &["liblzma5"],
            provides: &["xz-utils"],
            conflicts: &["xz-utils"],
            replaces: &["xz-utils"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "zstd",
            description: "Zstandard compression tools built for MattOS",
            source_component: "zstd",
            depends: &["libzstd1"],
            provides: &["zstd"],
            conflicts: &["zstd"],
            replaces: &["zstd"],
            essential: false,
            priority: "required",
        },
        PackageSpec {
            name: "patch",
            description: "GNU patch utility built for MattOS",
            source_component: "patch",
            depends: &["libattr1"],
            provides: &["patch"],
            conflicts: &["patch"],
            replaces: &["patch"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libmagic1",
            description: "libmagic runtime and compiled magic database built for MattOS",
            source_component: "file",
            depends: &["zlib1g"],
            provides: &["libmagic1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "file",
            description: "File type identification utility built for MattOS",
            source_component: "file",
            depends: &["libmagic1", "zlib1g"],
            provides: &["file"],
            conflicts: &["file"],
            replaces: &["file"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "less",
            description: "Interactive terminal pager built for MattOS",
            source_component: "less",
            depends: &["mattos-libtinfow6", "libpcre2-8-0"],
            provides: &["less"],
            conflicts: &["less"],
            replaces: &["less"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "git",
            description: "Git distributed version control with HTTPS support built for MattOS",
            source_component: "git",
            depends: &[
                "curl",
                "ca-certificates",
                "zlib1g",
                "libzstd1",
                "libexpat1",
                "libpcre2-8-0",
                "mattos-libcrypto3",
                "libssl3t64",
            ],
            provides: &["git"],
            conflicts: &["git"],
            replaces: &["git"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "openssh-client",
            description: "OpenSSH client tools built for MattOS",
            source_component: "openssh",
            depends: &["zlib1g", "libzstd1", "mattos-libcrypto3", "libssl3t64"],
            provides: &["ssh-client"],
            conflicts: &["openssh-client"],
            replaces: &["openssh-client"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "openssh-server",
            description: "OpenSSH secure shell server and MattOS service configuration",
            source_component: "openssh",
            depends: &[
                "openssh-client",
                "libpam0g",
                "libpam-runtime",
                "libcrypt1",
                "zlib1g",
                "libzstd1",
                "mattos-libcrypto3",
                "libssl3t64",
            ],
            provides: &["ssh-server"],
            conflicts: &["openssh-server"],
            replaces: &["openssh-server"],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libffi8",
            description: "Foreign-function interface runtime library built for MattOS",
            source_component: "libffi",
            depends: &["libc6"],
            provides: &["libffi8"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libffi-dev",
            description: "Foreign-function interface development files built for MattOS",
            source_component: "libffi",
            depends: &["libffi8", "libc6-dev"],
            provides: &["libffi-dev"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libwayland-client0",
            description: "Wayland client runtime library built for MattOS",
            source_component: "wayland",
            depends: &["libc6", "libffi8"],
            provides: &["libwayland-client0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libwayland-egl1",
            description: "Wayland EGL window runtime library built for MattOS",
            source_component: "wayland",
            depends: &["libc6", "libwayland-client0"],
            provides: &["libwayland-egl1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libwayland-server0",
            description: "Wayland compositor protocol runtime library built for MattOS",
            source_component: "wayland",
            depends: &["libc6", "libffi8"],
            provides: &["libwayland-server0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libxkbcommon0",
            description: "XKB keyboard description runtime library built for MattOS",
            source_component: "xkbcommon",
            depends: &["libc6", "xkb-data"],
            provides: &["libxkbcommon0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "xkb-data",
            description: "X Keyboard Extension data files built from pinned xkeyboard-config source",
            source_component: "xkeyboard-config",
            depends: &[],
            provides: &["xkb-data"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libseat1",
            description: "Seat management runtime library built for MattOS",
            source_component: "seatd",
            depends: &["libc6", "libsystemd0"],
            provides: &["libseat1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libdisplay-info3",
            description: "Display information parsing runtime library built for MattOS",
            source_component: "libdisplay-info",
            depends: &["libc6"],
            provides: &["libdisplay-info3"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libevdev2",
            description: "Linux input event runtime library built for MattOS",
            source_component: "libevdev",
            depends: &["libc6"],
            provides: &["libevdev2"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libinput10",
            description: "Input device handling runtime library built for MattOS",
            source_component: "libinput",
            depends: &["libc6", "libevdev2", "libudev1"],
            provides: &["libinput10"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libpixman-1-0",
            description: "Pixel manipulation runtime library built for MattOS",
            source_component: "pixman",
            depends: &["libc6"],
            provides: &["libpixman-1-0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libdrm2",
            description: "Direct Rendering Manager userspace runtime library built for MattOS",
            source_component: "libdrm",
            depends: &["libc6"],
            provides: &["libdrm2"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libdrm-amdgpu1",
            description: "AMDGPU DRM userspace runtime library built for MattOS",
            source_component: "libdrm",
            depends: &["libc6", "libdrm2"],
            provides: &["libdrm-amdgpu1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libdrm-nouveau2",
            description: "Nouveau DRM userspace runtime library built for MattOS",
            source_component: "libdrm",
            depends: &["libc6", "libdrm2"],
            provides: &["libdrm-nouveau2"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libxau6",
            description: "Minimal X authority ABI required by the NVIDIA Vulkan vendor library",
            source_component: "x11-compat",
            depends: &["libc6"],
            provides: &["libxau6"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libxdmcp6",
            description: "Minimal XDMCP ABI required by the NVIDIA Vulkan vendor library",
            source_component: "x11-compat",
            depends: &["libc6"],
            provides: &["libxdmcp6"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libxcb1",
            description: "X protocol transport ABI required by the NVIDIA Vulkan vendor library",
            source_component: "x11-compat",
            depends: &["libc6", "libxau6", "libxdmcp6"],
            provides: &["libxcb1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libx11-6",
            description: "X11 client ABI retained privately for NVIDIA Vulkan loader compatibility",
            source_component: "x11-compat",
            depends: &["libc6", "libxau6", "libxdmcp6", "libxcb1"],
            provides: &["libx11-6"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libxext6",
            description: "X11 extension ABI retained privately for NVIDIA Vulkan loader compatibility",
            source_component: "x11-compat",
            depends: &["libc6", "libxau6", "libxdmcp6", "libxcb1", "libx11-6"],
            provides: &["libxext6"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libglvnd0",
            description: "GLVND neutral OpenGL dispatch runtime built for MattOS",
            source_component: "libglvnd",
            depends: &["libc6"],
            provides: &["libglvnd0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libglx0",
            description: "GLVND GLX dispatch runtime built for MattOS",
            source_component: "libglvnd",
            depends: &[
                "libc6",
                "libglvnd0",
                "libx11-6",
                "libxcb1",
                "libxau6",
                "libxdmcp6",
            ],
            provides: &["libglx0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libgl1",
            description: "GLVND legacy OpenGL dispatch runtime built for MattOS",
            source_component: "libglvnd",
            depends: &[
                "libc6",
                "libglvnd0",
                "libglx0",
                "libx11-6",
                "libxcb1",
                "libxau6",
                "libxdmcp6",
            ],
            provides: &["libgl1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libopengl0",
            description: "GLVND neutral OpenGL API runtime built for MattOS",
            source_component: "libglvnd",
            depends: &["libc6", "libglvnd0"],
            provides: &["libopengl0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libgbm1",
            description: "Mesa GBM runtime library built for MattOS",
            source_component: "mesa",
            depends: &["libc6", "libdrm2"],
            provides: &["libgbm1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libegl1",
            description: "GLVND neutral EGL dispatch runtime built for MattOS",
            source_component: "libglvnd",
            depends: &["libc6", "libglvnd0"],
            provides: &["libegl1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libgles1",
            description: "GLVND neutral OpenGL ES 1 dispatch runtime built for MattOS",
            source_component: "libglvnd",
            depends: &["libc6", "libglvnd0"],
            provides: &["libgles1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libgles2",
            description: "GLVND neutral OpenGL ES 2 dispatch runtime built for MattOS",
            source_component: "libglvnd",
            depends: &["libc6", "libglvnd0"],
            provides: &["libgles2"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libegl-mesa0",
            description: "Mesa EGL vendor implementation and GLVND registration",
            source_component: "mesa",
            depends: &[
                "libc6",
                "libegl1",
                "libgbm1",
                "libdrm2",
                "libdrm-amdgpu1",
                "libdrm-nouveau2",
                "libelf1t64",
                "libexpat1",
                "libffi8",
                "libgcc-s1",
                "libgl1-mesa-dri",
                "libllvm22",
                "libstdc++6",
                "libwayland-client0",
                "libwayland-egl1",
                "libzstd1",
                "zlib1g",
            ],
            provides: &["libegl-mesa0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libgl1-mesa-dri",
            description: "Mesa DRI drivers for modern hardware, virtual GPUs, and software fallback",
            source_component: "mesa",
            depends: &[
                "libc6",
                "libgcc-s1",
                "libstdc++6",
                "libllvm22",
                "libdrm2",
                "libdrm-amdgpu1",
                "libdrm-nouveau2",
                "libgbm1",
                "libexpat1",
                "libelf1t64",
                "zlib1g",
                "libzstd1",
            ],
            provides: &[
                "libgl1-mesa-dri",
                "mattos-mesa-llvmpipe",
                "mattos-mesa-virgl",
            ],
            conflicts: &[],
            replaces: &["mattos-mesa-llvmpipe"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libvulkan1",
            description: "Khronos Vulkan loader runtime built for MattOS",
            source_component: "vulkan-loader",
            depends: &["libc6"],
            provides: &["libvulkan1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libvulkan-dev",
            description: "Khronos Vulkan headers and loader development metadata for MattOS",
            source_component: "vulkan-loader",
            depends: &["libc6-dev", "libvulkan1"],
            provides: &["libvulkan-dev"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "mesa-vulkan-drivers",
            description: "Mesa Vulkan ICDs for AMD, Intel, Nouveau, VirtIO, and software rendering",
            source_component: "mesa",
            depends: &[
                "libc6",
                "libvulkan1",
                "libgcc-s1",
                "libstdc++6",
                "libllvm22",
                "libdrm2",
                "libdrm-amdgpu1",
                "libdrm-nouveau2",
                "libgbm1",
                "libexpat1",
                "libelf1t64",
                "libwayland-client0",
                "libdisplay-info3",
                "libudev1",
                "zlib1g",
                "libzstd1",
            ],
            provides: &["mesa-vulkan-drivers"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "vulkan-tools",
            description: "Wayland and direct-display Vulkan diagnostics built for MattOS",
            source_component: "vulkan-tools",
            depends: &[
                "libc6",
                "libffi8",
                "libgcc-s1",
                "libstdc++6",
                "libvulkan1",
                "libwayland-client0",
            ],
            provides: &["vulkan-tools"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "linux-modules-nvidia-595-open-7.2.0-rc5-mattos",
            description: "NVIDIA 595.84 open GPU kernel modules for the exact MattOS kernel",
            source_component: "nvidia-driver",
            depends: &[
                "linux-modules-7.2.0-rc5-mattos",
                "nvidia-firmware-595",
                "kmod",
            ],
            provides: &["nvidia-open-kernel-modules", "nvidia-kernel-support-any"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "nvidia-firmware-595",
            description: "Matching NVIDIA 595.84 GSP firmware for Turing and newer GPUs",
            source_component: "nvidia-driver",
            depends: &["mattos-filesystem"],
            provides: &["firmware-nvidia-gsp", "nvidia-kernel-common-595"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libnvidia-gl-595",
            description: "NVIDIA 595.84 EGL, OpenGL ES, Vulkan, GBM, and Wayland vendor stack",
            source_component: "nvidia-driver",
            depends: &[
                "libc6",
                "libexpat1",
                "libffi8",
                "libgcc-s1",
                "libglvnd0",
                "libegl1",
                "libgles1",
                "libgles2",
                "libopengl0",
                "libdrm2",
                "libgbm1",
                "libwayland-client0",
                "libwayland-server0",
                "libxau6",
                "libxdmcp6",
                "libxcb1",
                "libx11-6",
                "libxext6",
                "libnvidia-compute-595",
            ],
            provides: &["nvidia-vulkan-icd", "nvidia-egl-icd", "nvidia-driver-libs"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libnvidia-compute-595",
            description: "NVIDIA 595.84 CUDA driver, NVML, and shader compiler runtime",
            source_component: "nvidia-driver",
            depends: &["libc6"],
            provides: &["libcuda1", "libnvidia-ml1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libnvidia-encode-595",
            description: "NVIDIA 595.84 NVENC video encoding runtime",
            source_component: "nvidia-driver",
            depends: &["libc6", "libnvidia-compute-595", "libnvidia-decode-595"],
            provides: &["libnvidia-encode1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libnvidia-decode-595",
            description: "NVIDIA 595.84 NVDEC video decoding runtime",
            source_component: "nvidia-driver",
            depends: &["libc6", "libnvidia-compute-595"],
            provides: &["libnvcuvid1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "nvidia-utils-595",
            description: "NVIDIA 595.84 nvidia-smi, module helper, and persistence utilities",
            source_component: "nvidia-driver",
            depends: &[
                "libc6",
                "libnvidia-compute-595",
                "linux-modules-nvidia-595-open-7.2.0-rc5-mattos",
            ],
            provides: &["nvidia-smi"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "nvidia-driver-595-open",
            description: "Complete official NVIDIA 595.84 open-kernel Wayland graphics stack",
            source_component: "nvidia-driver",
            depends: &[
                "linux-modules-nvidia-595-open-7.2.0-rc5-mattos",
                "libnvidia-gl-595",
                "libnvidia-compute-595",
                "libnvidia-encode-595",
                "libnvidia-decode-595",
                "nvidia-utils-595",
            ],
            provides: &["nvidia-driver", "nvidia-driver-any"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "cosmic-comp",
            description: "COSMIC Wayland compositor for MattOS graphical sessions",
            source_component: "cosmic-comp",
            depends: &[
                "libc6",
                "libgcc-s1",
                "libstdc++6",
                "libseat1",
                "libdisplay-info3",
                "libinput10",
                "libpixman-1-0",
                "libgbm1",
                "libegl1",
                "libgles1",
                "libgles2",
                "libgl1-mesa-dri",
                "libwayland-client0",
                "libxkbcommon0",
                "libudev1",
            ],
            provides: &["cosmic-comp"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "flatpak",
            description: "Flatpak application runtime and sandbox manager built from pinned upstream source",
            source_component: "flatpak",
            depends: &[
                "libc6",
                "libglib2.0-0t64",
                "curl",
                "libcap2",
                "libsystemd0",
                "libdbus-1-3",
                "libzstd1",
                "gnupg",
                "polkit",
            ],
            provides: &["flatpak", "libflatpak0"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "xwayland",
            description: "Target-built Xwayland server and its closed X11 rendering runtime",
            source_component: "xwayland",
            depends: &[
                "libc6",
                "libpixman-1-0",
                "libx11-6",
                "libxext6",
                "libxdmcp6",
                "libmd0",
                "libxcb1",
                "libwayland-client0",
                "libxkbcommon0",
                "libdrm2",
                "libgbm1",
                "libegl1",
                "libgl1",
                "libgl1-mesa-dri",
                // Xwayland invokes the target-owned xkbcomp helper to load
                // keyboard maps from xkeyboard-config at startup.
                "xkb-data",
            ],
            provides: &["xwayland"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "xdg-desktop-portal",
            description: "Freedesktop desktop portal broker for Flatpak and COSMIC applications",
            source_component: "xdg-desktop-portal",
            depends: &[
                "libc6",
                "libglib2.0-0t64",
                "libdbus-1-3",
                "libsystemd0",
                "pipewire",
                "flatpak",
            ],
            provides: &["xdg-desktop-portal"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "cosmic-desktop",
            description: "Complete source-built COSMIC desktop and graphical login for MattOS",
            source_component: "cosmic-desktop",
            depends: &[
                // Live graphics probing/recovery uses existing target tools.
                "coreutils",
                "procps",
                "mattos-sudo-rs",
                "util-linux",
                "kmod",
                "cosmic-comp",
                "dbus-broker",
                "libdbus-1-3",
                "libdav1d7",
                "libglib2.0-0t64",
                "pipewire",
                "libpam0g",
                "libpam-modules",
                "libpam-runtime",
                "libsystemd0",
                "flatpak",
                "xwayland",
                "xdg-desktop-portal",
                "udev",
                "libwayland-client0",
                "libxkbcommon0",
                "xkb-data",
                "libgbm1",
                "libegl1",
                "libgl1-mesa-dri",
                "mesa-vulkan-drivers",
            ],
            provides: &[
                "cosmic-session",
                "cosmic-greeter",
                "cosmic-panel",
                "cosmic-launcher",
                "cosmic-settings",
                "cosmic-settings-daemon",
                "cosmic-notifications",
                "cosmic-osd",
                "cosmic-bg",
                "cosmic-idle",
                "cosmic-workspaces",
                "cosmic-files",
                "cosmic-term",
                "cosmic-ext-calculator",
                "cosmic-ext-storage",
                "cosmic-monitor",
                "cosmic-store",
                "greetd",
            ],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "cosmic-edit",
            description: "COSMIC Text Editor built from the pinned upstream source",
            source_component: "cosmic-edit",
            depends: &["libc6", "libgcc-s1", "libstdc++6", "cosmic-desktop"],
            provides: &[],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "cosmic-initial-setup",
            description: "COSMIC first-login setup wizard built from the pinned upstream source",
            source_component: "cosmic-initial-setup",
            depends: &[
                "libc6",
                "libgcc-s1",
                "libstdc++6",
                "cosmic-desktop",
                "network-manager",
                "iso-codes",
            ],
            provides: &["cosmic-initial-setup"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libduktape207",
            description: "Duktape JavaScript engine runtime built from the pinned upstream source",
            source_component: "duktape",
            depends: &["libc6"],
            provides: &["libduktape.so.207"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "polkit",
            description: "Source-built PolicyKit authorization service and agent helper",
            source_component: "polkit",
            depends: &[
                "libc6",
                "libglib2.0-0t64",
                "libpam0g",
                "libpam-modules",
                "libpam-runtime",
                "libdbus-1-3",
                "libsystemd0",
                "libduktape207",
            ],
            provides: &["polkit-1"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "network-manager",
            description: "Source-built NetworkManager daemon, D-Bus API, and nmcli",
            source_component: "networkmanager",
            depends: &[
                "libc6",
                "libglib2.0-0t64",
                "libsystemd0",
                "libdbus-1-3",
                "polkit",
                "iproute2",
                "libndp0",
                "libreadline8",
                "libncursesw6",
                "mattos-libtinfow6",
                "wpasupplicant",
            ],
            provides: &["network-manager", "networkmanager"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "libnl-3-200",
            description: "Netlink core runtime library",
            source_component: "libnl",
            depends: &["libc6"],
            provides: &[], conflicts: &[], replaces: &[], essential: false, priority: "important",
        },
        PackageSpec {
            name: "libnl-genl-3-200",
            description: "Generic Netlink runtime library",
            source_component: "libnl",
            depends: &["libc6", "libnl-3-200"],
            provides: &[], conflicts: &[], replaces: &[], essential: false, priority: "important",
        },
        PackageSpec {
            name: "wpasupplicant",
            description: "WPA2/WPA3 and enterprise Wi-Fi supplicant with D-Bus activation",
            source_component: "wpa-supplicant",
            depends: &["libc6", "libssl3t64", "mattos-libcrypto3", "libdbus-1-3", "dbus-broker", "libnl-3-200", "libnl-genl-3-200"],
            provides: &[], conflicts: &[], replaces: &[], essential: false, priority: "important",
        },
        PackageSpec {
            name: "grub-efi-amd64",
            description: "Source-built GRUB boot manager, EFI modules and standard configuration tools",
            source_component: "grub",
            depends: &["libc6", "liblzma5", "zlib1g", "coreutils", "mattos-brush"],
            provides: &[], conflicts: &[], replaces: &[], essential: false, priority: "important",
        },
        PackageSpec {
            name: "mattos-cozy",
            description: "Cozy terminal text editor built from the pinned upstream source",
            source_component: "cozy",
            depends: &["libc6", "libgcc-s1"],
            provides: &[],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libpython3.14",
            description: "CPython 3.14 shared runtime library built for MattOS",
            source_component: "cpython",
            depends: &["libc6"],
            provides: &["libpython3.14"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "python3",
            description: "CPython interpreter and standard library built for MattOS",
            source_component: "cpython",
            depends: &[
                "libpython3.14",
                "libffi8",
                "mattos-libcrypto3",
                "libssl3t64",
                "zlib1g",
                "libbz2-1.0",
                "liblzma5",
                "libexpat1",
                "libzstd1",
                "libncursesw6",
                "mattos-libtinfow6",
                "libuuid1",
            ],
            provides: &["python3"],
            conflicts: &["python3"],
            replaces: &["python3"],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "python3-venv",
            description: "CPython virtual-environment and ensurepip support built for MattOS",
            source_component: "cpython",
            depends: &["python3"],
            provides: &["python3-venv"],
            conflicts: &["python3-venv"],
            replaces: &["python3-venv"],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "python3-dev",
            description: "CPython headers and native extension development files built for MattOS",
            source_component: "cpython",
            depends: &["python3", "libpython3.14", "libffi-dev", "libc6-dev"],
            provides: &["python3-dev"],
            conflicts: &["python3-dev"],
            replaces: &["python3-dev"],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "libllvm22",
            description: "LLVM 22 shared runtime library built for MattOS",
            source_component: "llvm",
            depends: &["libc6", "libgcc-s1", "libstdc++6", "zlib1g", "libzstd1"],
            provides: &["libllvm22"],
            conflicts: &[],
            replaces: &[],
            essential: false,
            priority: "important",
        },
        PackageSpec {
            name: "llvm",
            description: "LLVM development command-line tools built for MattOS",
            source_component: "llvm",
            depends: &[
                "libllvm22",
                "libc6",
                "libgcc-s1",
                "libstdc++6",
                "zlib1g",
                "libzstd1",
            ],
            provides: &["llvm"],
            conflicts: &["llvm"],
            replaces: &["llvm"],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "llvm-dev",
            description: "LLVM headers and CMake development metadata built for MattOS",
            source_component: "llvm",
            depends: &["llvm", "libllvm22", "libc6-dev", "mattos-libstdc++-dev"],
            provides: &["llvm-dev"],
            conflicts: &["llvm-dev"],
            replaces: &["llvm-dev"],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "clang",
            description: "Clang C and C++ compiler built for MattOS",
            source_component: "llvm",
            depends: &[
                "libllvm22",
                "libc6",
                "libgcc-s1",
                "libstdc++6",
                "zlib1g",
                "libzstd1",
                "libc6-dev",
                "mattos-libgcc-dev",
                "mattos-libstdc++-dev",
                "binutils",
            ],
            provides: &["clang"],
            conflicts: &["clang"],
            replaces: &["clang"],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "lld",
            description: "LLVM linker built for MattOS",
            source_component: "llvm",
            depends: &[
                "libllvm22",
                "libc6",
                "libgcc-s1",
                "libstdc++6",
                "zlib1g",
                "libzstd1",
            ],
            provides: &["lld"],
            conflicts: &["lld"],
            replaces: &["lld"],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "rustc",
            description: "Rust compiler, standard library, and rustdoc built for MattOS",
            source_component: "rust",
            depends: &[
                "libc6",
                "libgcc-s1",
                "libstdc++6",
                "libllvm22",
                "zlib1g",
                "libzstd1",
                "gcc",
                "binutils",
                "libc6-dev",
            ],
            provides: &["rustc", "rustdoc"],
            conflicts: &["rustc"],
            replaces: &["rustc"],
            essential: false,
            priority: "optional",
        },
        PackageSpec {
            name: "cargo",
            description: "Cargo Rust package manager built for MattOS",
            source_component: "rust",
            depends: &[
                "rustc",
                "libgcc-s1",
                "git",
                "ca-certificates",
                "mattos-libcrypto3",
                "libssl3t64",
                "zlib1g",
                "libzstd1",
            ],
            provides: &["cargo"],
            conflicts: &["cargo"],
            replaces: &["cargo"],
            essential: false,
            priority: "optional",
        },
    ]
}

pub(crate) fn package_install_order() -> Result<Vec<&'static str>> {
    let specs = package_specs();
    package_install_order_for(&specs, PACKAGE_NAMES)
}

pub(crate) fn package_install_order_for(
    specs: &[PackageSpec],
    preference: &[&'static str],
) -> Result<Vec<&'static str>> {
    let names: BTreeSet<&str> = specs.iter().map(|spec| spec.name).collect();
    let mut remaining: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for spec in specs {
        let mut dependencies = BTreeSet::new();
        for dependency in spec.depends.iter().copied() {
            if names.contains(dependency) {
                dependencies.insert(dependency);
            } else {
                bail!(
                    "package {} depends on unknown package {dependency}",
                    spec.name
                )
            }
        }
        remaining.insert(spec.name, dependencies);
    }
    let mut installed = BTreeSet::new();
    let mut order = Vec::new();
    while !remaining.is_empty() {
        let next = preference.iter().copied().find(|name| {
            remaining
                .get(name)
                .is_some_and(|dependencies| dependencies.is_subset(&installed))
        });
        let Some(next) = next else {
            let cycle = remaining.keys().copied().collect::<Vec<_>>().join(", ");
            bail!("circular or unresolvable MattOS package dependencies: {cycle}")
        };
        remaining.remove(next);
        installed.insert(next);
        order.push(next);
    }
    Ok(order)
}
