"""Shared helpers for independently maintained MattOS third-party packages."""

from .framework import (
    BuildResult,
    PackageRecipe,
    PublishedPackage,
    ReleaseSelection,
    RecipeError,
    SourceReleaseRecipe,
    autotools_build_install,
    build_in_container,
    build_inputs_digest,
    builder_image,
    cmake_build_install,
    command,
    download,
    ensure_not_a_mattos_package,
    extract_archive,
    fetch_json,
    finalize_package,
    github_latest_release,
    github_source_archive,
    make_build_install,
    mattos_package_names,
    package_staging,
    parse_packages_index,
    read_repository_inventory,
    release_selections,
    release_state,
    repository_inventory,
    require_tools,
    run_recipe,
    sha256_file,
    validate_package_artifact,
    validate_repository,
    write_control,
    write_provenance,
    write_repository_inventory,
)

__all__ = [
    "BuildResult", "PackageRecipe", "PublishedPackage", "RecipeError", "ReleaseSelection",
    "SourceReleaseRecipe", "autotools_build_install", "build_in_container", "build_inputs_digest",
    "builder_image", "cmake_build_install", "command", "download", "ensure_not_a_mattos_package",
    "extract_archive", "fetch_json", "finalize_package", "github_latest_release",
    "github_source_archive", "make_build_install", "mattos_package_names", "package_staging",
    "parse_packages_index", "read_repository_inventory", "release_selections", "release_state",
    "repository_inventory", "require_tools", "run_recipe", "sha256_file",
    "validate_package_artifact", "validate_repository", "write_control", "write_provenance",
    "write_repository_inventory",
]
